### ISSUE TITLE
全角で取得している番組タイトルを半角に揃えて変換してもらいたいのですが、

### ISSUE THREAD

**Issue by Beems360** [Chinachu/Chinachu#193]
多分、放送局の都合で全角で取得しているのだろうと思いますが、検索時に、例えば　ABCDまたはABCDの検索を両方しなくては地上、BS,CSでの検索時に都合が悪いです。
また、ルールーを書くときに、半角、全角、等、取得したタイトルに合わせて登録しなくてはならないため、手間がかかります。
例えば、　地上波では半角なのに、BS,CSでは全角の場合（ほとんどそうなのですが）一つのルールーに２つのキーワードを書かなくてはなりません
例　ABC,ABC　もしくは　半角アルファベットABC半角スペースDEF,全角アルファベットABC全角スペースDEF　等です。

この辺りを半角に統一出来るようになれば、検索も楽になりますし、登録も楽になります。

よろしくおねがいします。

**Comment by Beems360** [comment]
書き忘れましたが、こんなケースもあります
例
あいうえお半角スペースかきくけこ　あいうえお全角スペースかきくけこ

こんなかんじです

**Comment by kounoike** [comment]
https://www.npmjs.com/package/moji のconvertを使ってルールとプログラムタイトル等を正規化して検索すれば良さそうですね。
forkした自分のとこで試しに作ってみようかと思います。上手く出来たらPRしたいと思います。
WORKINGが終わらないうちに出来ると良いのですが。

**Comment by kounoike** [comment]
@Beems360 http://nomenclator.la.coocan.jp/unicode/normalization.htm にあるNFKCによる変換をルールとプログラムタイトル等の両方にかければ良い感じでしょうか？
色々な処理が入ってますが、

* 全角英数字の半角化
* 全角空白の半角化

は入っています。他にも

* 丸数字の半角数字化
* 半角カナの全角化
* 全角記号の半角化

などが入っています。

**Comment by kounoike** [comment]
@Beems360 
PRも出してますが、https://github.com/kounoike/Chinachu/tree/my-server でうちで使ってる状態にしてあります。
