### ISSUE TITLE
スマホで番組表を表示後にすぐタップするとエラーが発生する。

### ISSUE THREAD

**Issue by epgdatacapbon** [Chinachu/Chinachu#194]
AndroidもしくはiPhoneでChinachuにアクセスし、番組表を表示後すぐに（番組表をスクロールせずに）、いずれかの番組をタップして番組詳細を表示させようとすると、Androidでは「ERROR: http://xxxxxxxx/#!/schedule/table/:730 Uncaught TypeError: Cannot read property '0' of undefined」（Chrome）、iPhoneでは「ERROR: undefined:722 TypeError: 'undefined' is not an object」（Safari, Chromeとも）と表示されます。番組表をすこしでもスクロールしてからタップした場合はエラーは表示されません。なお、エラーをタップすると番組表が再読み込み（一旦消えて読みなおす）されます。
表示端末はAndroidは4.4、iPhone4はiOS6.1.3です。

Chinachuは「610b0ce717f6e7bad62a032a59e10d860547f08b」で、Raspberry Pi 2のRaspbianにインストールしており、鍵を設定してTLSで使っています。

**Comment by kanreisa** [comment]
再現しました。
