### ISSUE TITLE
DLNA/UPnP機能をオンにしても、機能が有効にならない

### ISSUE THREAD

**Issue by shirow-github** [Chinachu/Chinachu#229]
本日、git masterの最新版に上げてconfig.jsonに「"wuiDLNAServerEnabled": true,」を追加しても、
DLNA/UPnP機能を使うことが出来ませんでした。

環境
Windows 7 SP1 x64/Windows Media player

また、Wuiログには以下の様なメッセージが出力されています。
'-------------------------------------------------------
info: socket.io started
info: socket.io started
24 Sep 20:49:27 - HTTPS Server Listening on { address: '::', family: 'IPv6', port: 10772 }
Ready http://[::]:20773
{"name":"ssdp-server","hostname":"mythtv.dip.jp","pid":3823,"level":50,"err":{"message":"bind EADDRINUSE 0.0.0.0:1900","name":"Error","stack":"Error: bind EADDRINUSE 0.0.0.0:1900\n at Object.exports._errnoException (util.js:837:11)\n at exports._exceptionWithHostPort (util.js:860:20)\n at dgram.js:213:18\n at doNTCallback3 (node.js:440:9)\n at process._tickCallback (node.js:346:17)\n at Function.Module.runMain (module.js:477:11)\n at startup (node.js:117:18)\n at node.js:951:3","code":"EADDRINUSE"},"msg":"Socker error","time":"2015-09-24T11:49:27.633Z","src":{"file":"/home/chinachu/chinachu/node_modules/chinachu-upnp-server/node_modules/node-ssdp/lib/index.js","line":166,"func":"onSocketError"},"v":0}

**Comment by kounoike** [comment]
Error: bind EADDRINUSE 0.0.0.0:1900 とあるので、他のプロセスが1900ポートを開いているのではないでしょうか。sudo netstat -nap | grep 1900 としてみるとどうでしょう？

ちなみにうちでもwuiDLNAServerEnabledを立ててみましたが、エクスプローラのネットワークでメディア機器としては認識されるのですが、WMP（＠Win7）では見えないという状態でした。

**Comment by shirow-github** [comment]
$ sudo netstat -nap | grep 1900
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           10873/java
udp        0      0 239.255.255.250:1900    0.0.0.0:*                           10857/minidlnad

仰るとおり、DLNA/UPnP関係の別のソフトとコンフリクトしてたようです。
※ちなみに、java(BubbleUPnPserver)、minidlnad(MiniDLNA)です。

上記2つのソフトを停止後、Chinachu関連を再起動したところ、Chinachu(beta)と出てきました。
$ sudo netstat -nap | grep 1900
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           11336/node

また、Wuiのログは以下のようになりました。
'--------------------------------------------------------
Ready http://[::]:20773
{"name":"ssdp-server","hostname":"mythtv.dip.jp","pid":11336,"level":30,"address":"http://0.0.0.0:1900","msg":"SSDP listening","time":"2015-09-24T15:15:00.809Z","src":{"file":"/home/chinachu/chinachu/node_modules/chinachu-upnp-server/node_modules/node-ssdp/lib/index.js","line":176,"func":"onSocketListening"},"v":0}
{"name":"ssdp-server","hostname":"mythtv.dip.jp","pid":11336,"level":30,"msg":"UDP socket bound { host: '0.0.0.0', port: 1900 }","time":"2015-09-24T15:15:00.811Z","src":{"file":"/home/chinachu/chinachu/node_modules/chinachu-upnp-server/node_modules/node-ssdp/lib/server.js","line":46,"func":"SsdpServer._initAdLoop"},"v":0}
'--------------------------------------------------------

こちらも、Win7環境ではメディア機器として認識するものの、WMPでは認識されません。

またSlack上の動作確認済みであるWin10 X64+ffdshow 32bit環境(当方VMWare12上の仮想環境)では、
メディア機器及びWMP上の認識は確認出来ました。

しかし、WMP上でファイルをクリックしても再生されません。
※Chinachu(bata) → ビデオ → すべてのビデオ → 録画ファイル名をクリック
