### ISSUE TITLE
ルール仕様についての質問

### ISSUE THREAD

**Issue by goodyears2016** [Chinachu/Chinachu#253]
ちょっと録画ルールに関する仕様について教えて下さい。
タイトルで以下の番組を録画しようとしています。
ヒストリーチャンネル: ［二］タイニーハウス〜大きなアメリカの極端に小さな家〜 (2015/12/02 23:00)
タイニーハウス
タイニーハウス〜大きなアメリカの極端に小さな家〜
上記のいずれかをルールのタイトルに指定してスケジューラーの実行をしても
録画予約されないのですが
［二］タイニーハウス〜大きなアメリカの極端に小さな家〜
と指定してスケジューラーの実行をすればすぐに予約開始されます。
最初の２つの指定方法には何がダメなのでしょうか？？

あと、Chinachu Airの詳しいリリース日分かる方いませんか？

**Comment by simplelife0530** [comment]
前半の質問には答えられませんが、
後半の質問に興味があります。
＞あと、Chinachu Airの詳しいリリース日分かる方いませんか？
2015年末と予定が告知されていますが、本当にリリースされるのでしょうか。

1台Anime Lockerをインストールしてしまおうかと思っているサーバーがあるのですが、Chinachu Airのために、半年寝かしてあります。クリスマスプレゼントにリリースか？と期待しております。
