### ISSUE TITLE
iOSデバイスからの視聴について

### ISSUE THREAD

**Issue by arkmarou** [Chinachu/Chinachu#259]
iOSデバイスからライブ視聴をする場合、
①番組表の放送局名を右クリックしてコンテキストメニューを表示させライブ視聴ボタンを押すことができません。
→URL直打ちでページを開くことは可能でした。
②ライブ視聴画面を開いても、コンテナの選択が表示されません。
→更新ボタンを長押しし、デスクトップ版を表示とすることで表示されるようになりました。
③再生を押してもストリーミングで再生されません。
→MP4を選択していても再生が始まらず、ffmpegも起動していないようでした。
④iPhoneで表示させると、レスポンシブのせいか押せないボタンが出てきてしまいます。
→iPadであれば画面も広いのでほとんどのボタンを押すことができました。

これらを解決する方法はありますでしょうか？
よろしくお願いいたします。

**Comment by kanreisa** [comment]
とても良くない仕組みだったので一旦廃止しています。
Air で再実装される予定です。

**Comment by arkmarou** [comment]
kanreisa様

返信ありがとうございます。
Chinachu Air、首を長く長くして待っております。
よろしくお願いします！

**Comment by kanreisa** [comment]
@arkmarou 
暖かいお言葉、ありがとうございます。
この issue は目印用に開いたままにします。

**Comment by kanreisa** [comment]
[gamma](https://r2.ag/chinachu-gamma/) でiOS対応しました。
