### ISSUE TITLE
Chinachu最新版に更新後、録画ファイルのプレビュー画像が作成されず、XSPF等でも再生不可になりました。

### ISSUE THREAD

**Issue by shirow-github** [Chinachu/Chinachu#263]
本日、Chinachu masterブランチの最新版に変更した所、録画ファイルのプレビュー画像が作成されず、XSPF等でも再生不可になりました。

※XSPFボタンを押してもxspfファイルがダウンロードされず、また再生ボタンを押してもブラウザ上で再生されません。
※ちなみに、番組表からのライブ視聴は今までどおり出来ております。

WUIログには、以下の様なエラーメッセージが表示されます。
'------------------------------------------------
3 Mar 22:25:15 - 200 GET:/api/recorded/gr63504-c97/file.json 192.168.11.5 "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36 Sleipnir/4.4.7"
3 Mar 22:25:15 - { [Error: Command failed: /bin/sh -c ffmpeg -f mpegts -ss 30.5 -r 10 -i "/home/my-video/tv/GR34-ゴッドタン-20160303_0128.m2ts" -ss 1.5 -r 10 -frames:v 1 -c:v mjpeg -an -f image2 -s 640x360 -map 0:0 -y pipe:1
]
killed: false,
code: null,
signal: 'SIGSEGV',
cmd: '/bin/sh -c ffmpeg -f mpegts -ss 30.5 -r 10 -i "/home/my-video/tv/GR34-ゴッドタン-20160303_0128.m2ts" -ss 1.5 -r 10 -frames:v 1 -c:v mjpeg -an -f image2 -s 640x360 -map 0:0 -y pipe:1' }
'------------------------------------------------

もしかしたら、ffmpegのスタティックビルドへ変更されたことでパスが通っていないのかも？
変更前のコミット（d982a48006ce774d83cdfd96e6f768cc394c2f69）に戻してみたところ、今までどおり再生出来ました。

**Comment by kanreisa** [comment]
installer は full で実行しましたか。installer のログには異常ないですか。

**Comment by shirow-github** [comment]
./chinachu installerで、1)Auto(full)を選択してインストールしたのですが、
特にログには異常は無さそうです。

'-------------------------------------------------------
Chinachu Installer Menu:
[!] These are installed under all /home/chinachu/chinachu/...
[!] Recommend the Auto installation.
1) Auto (full)          4) Node.js Environment  7) ffmpeg
2) Auto (fast)          5) Node.js Modules
3) submodule            6) epgdump
what do you install? > 1
selected: Auto (full)
removed `/home/chinachu/chinachu/.nave'
Installing Node using Nave...
--2016-03-05 17:50:23--  https://github.com/isaacs/nave/archive/v0.5.1.tar.gz
github.com をDNSに問いあわせています... 192.30.252.129
github.com|192.30.252.129|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 302 Found
場所: https://codeload.github.com/isaacs/nave/tar.gz/v0.5.1 [続く]
--2016-03-05 17:50:25--  https://codeload.github.com/isaacs/nave/tar.gz/v0.5.1
codeload.github.com をDNSに問いあわせています... 192.30.252.160
codeload.github.com|192.30.252.160|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 200 OK
長さ: 7640 (7.5K) [application/x-gzip]
`STDOUT' に保存中

-                              100%[=====================================================>]   7.46K  --.-KB/s 時間 0s     

2016-03-05 17:50:27 (64.7 MB/s) - stdout へ出力完了 [7640/7640]

nave-0.5.1/nave.sh
ディレクトリを削除しました: `/home/chinachu/chinachu/.nave/nave-0.5.1'

curl: (22) The requested URL returned error: 404 Not Found
######################################################################## 100.0%
installed from binary
`/home/chinachu/chinachu/.nave/node' -> `/home/chinachu/chinachu/.nave/installed/4.1.2/bin/node'
`/home/chinachu/chinachu/.nave/npm' -> `/home/chinachu/chinachu/.nave/installed/4.1.2/bin/npm'
done.
Installing Node Modules using NPM...
done.
Installing epgdump from 
--2016-03-05 17:51:19--  https://github.com/stz2012/epgdump/archive/master.tar.gz
github.com をDNSに問いあわせています... 192.30.252.131
github.com|192.30.252.131|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 302 Found
場所: https://codeload.github.com/stz2012/epgdump/tar.gz/master [続く]
--2016-03-05 17:51:20--  https://codeload.github.com/stz2012/epgdump/tar.gz/master
codeload.github.com をDNSに問いあわせています... 192.30.252.160
codeload.github.com|192.30.252.160|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 200 OK
長さ: 23983 (23K) [application/x-gzip]
`STDOUT' に保存中

-                              100%[=====================================================>]  23.42K  48.5KB/s 時間 0.5s   

2016-03-05 17:51:22 (48.5 KB/s) - stdout へ出力完了 [23983/23983]

epgdump-master/
epgdump-master/Makefile
epgdump-master/aribstr.c
epgdump-master/aribstr.h
epgdump-master/eit.c
epgdump-master/eit.h
epgdump-master/epgdump.c
epgdump-master/readme.txt
epgdump-master/sdt.c
epgdump-master/sdt.h
epgdump-master/tags
epgdump-master/ts.c
epgdump-master/ts.h
epgdump-master/ts_ctl.h
epgdump-master/util.c
epgdump-master/util.h
epgdump-master/xmldata.c
gcc -std=c99 -O2 -Wall -g -Wno-return-type  -c epgdump.c
gcc -std=c99 -O2 -Wall -g -Wno-return-type  -c aribstr.c
gcc -std=c99 -O2 -Wall -g -Wno-return-type  -c eit.c
gcc -std=c99 -O2 -Wall -g -Wno-return-type  -c ts.c
gcc -std=c99 -O2 -Wall -g -Wno-return-type  -c util.c
epgdump.c: In function 'main':
epgdump.c:147:7: warning: variable 'staCount' set but not used [-Wunused-but-set-variable]
  int  staCount ;
       ^
util.c: In function 'parseOTHERdesc':
util.c:80:6: warning: variable 'descriptor_tag' set but not used [-Wunused-but-set-variable]
  int descriptor_tag;
      ^
gcc -std=c99 -O2 -Wall -g -Wno-return-type  -c sdt.c
gcc -std=c99 -O2 -Wall -g -Wno-return-type  epgdump.o aribstr.o eit.o ts.o util.o sdt.o -o epgdump  
removed `/home/chinachu/chinachu/usr/src/epgdump'
epgdump --> done.
removed `/home/chinachu/chinachu/usr/src/ffmpeg'
--2016-03-05 17:51:22--  http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz
johnvansickle.com をDNSに問いあわせています... 199.79.62.21
johnvansickle.com|199.79.62.21|:80 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 200 OK
長さ: 15344076 (15M) [application/x-tar]
`ffmpeg-release-32bit-static.tar.xz' に保存中

ffmpeg-release-32bit-static.ta 100%[=====================================================>]  14.63M  96.6KB/s 時間 2m 28s 

2016-03-05 17:53:51 (101 KB/s) - `ffmpeg-release-32bit-static.tar.xz' へ保存完了 [15344076/15344076]

ffmpeg-release-32bit-static.tar.xz (1/1)
  100 %        14.6 MiB / 129.3 MiB = 0.113                   0:01             
ffmpeg-3.0-32bit-static/ffserver
ffmpeg-3.0-32bit-static/GPLv3.txt
ffmpeg-3.0-32bit-static/ffmpeg-10bit
ffmpeg-3.0-32bit-static/manpages/
ffmpeg-3.0-32bit-static/manpages/ffmpeg-all.txt
ffmpeg-3.0-32bit-static/manpages/ffserver.txt
ffmpeg-3.0-32bit-static/manpages/ffmpeg-bitstream-filters.pdf
ffmpeg-3.0-32bit-static/manpages/ffmpeg-scaler.txt
ffmpeg-3.0-32bit-static/manpages/ffmpeg-resampler.txt
ffmpeg-3.0-32bit-static/manpages/ffmpeg-devices.pdf
ffmpeg-3.0-32bit-static/manpages/ffmpeg-filters.txt
ffmpeg-3.0-32bit-static/manpages/ffmpeg-protocols.pdf
ffmpeg-3.0-32bit-static/manpages/ffmpeg-scaler.pdf
ffmpeg-3.0-32bit-static/manpages/ffprobe.txt
ffmpeg-3.0-32bit-static/manpages/ffmpeg-devices.txt
ffmpeg-3.0-32bit-static/manpages/ffmpeg.pdf
ffmpeg-3.0-32bit-static/manpages/ffmpeg-formats.pdf
ffmpeg-3.0-32bit-static/manpages/ffmpeg-codecs.pdf
ffmpeg-3.0-32bit-static/manpages/ffmpeg-utils.txt
ffmpeg-3.0-32bit-static/manpages/ffmpeg-resampler.pdf
ffmpeg-3.0-32bit-static/manpages/ffprobe.pdf
ffmpeg-3.0-32bit-static/manpages/ffmpeg-utils.pdf
ffmpeg-3.0-32bit-static/manpages/ffmpeg-protocols.txt
ffmpeg-3.0-32bit-static/manpages/ffmpeg-codecs.txt
ffmpeg-3.0-32bit-static/manpages/ffserver.pdf
ffmpeg-3.0-32bit-static/manpages/ffmpeg-filters.pdf
ffmpeg-3.0-32bit-static/manpages/ffmpeg-bitstream-filters.txt
ffmpeg-3.0-32bit-static/manpages/ffmpeg-all.pdf
ffmpeg-3.0-32bit-static/manpages/ffmpeg.txt
ffmpeg-3.0-32bit-static/manpages/ffmpeg-formats.txt
ffmpeg-3.0-32bit-static/ffprobe
ffmpeg-3.0-32bit-static/qt-faststart
ffmpeg-3.0-32bit-static/readme.txt
ffmpeg-3.0-32bit-static/ffmpeg
`ffmpeg-release-32bit-static.tar' を削除しました
Creating libav aliases...
`/home/chinachu/chinachu/usr/bin/avconv' を削除しました
`/home/chinachu/chinachu/usr/bin/avprobe' を削除しました
`/home/chinachu/chinachu/usr/bin/avconv' -> `/home/chinachu/chinachu/usr/bin/ffmpeg'
`/home/chinachu/chinachu/usr/bin/avprobe' -> `/home/chinachu/chinachu/usr/bin/ffprobe'
ffmpeg --> done.

**Comment by kanreisa** [comment]
セグメンテーション違反だと言われてますが、
`./chinachu test ffmpeg` は実行できますか？

**Comment by shirow-github** [comment]
$ ./chinachu test ffmpeg
./chinachu: 629 行: 20069 Segmentation fault      ${USR_DIR}/bin/"$@"
failed somehow

セグメンテーション違反が出るようです。

**Comment by kanreisa** [comment]
カーネルのバージョン, ディストリビューション, アーキテクチャ を参考までにください

**Comment by shirow-github** [comment]
カーネルのバージョン：4.1.18
ディストリビューション：Vine Linux Seed 32bit
アーキテクチャ：i686

と、なります。

**Comment by kanreisa** [comment]
`http://johnvansickle.com/ffmpeg/builds/ffmpeg-git-32bit-static.tar.xz`
これに差し替えてみて、ダメだったら gdb したほうが早そうですね

**Comment by shirow-github** [comment]
ffmpeg-git-32bit-static.tar.xzに差し替えてみましたが、結果はダメでした。
具体的にgdbは、どう使ったら良いですか？
