### ISSUE TITLE
録画ファイル名フォーマットについて

### ISSUE THREAD

**Issue by pick2** [Chinachu/Chinachu#266]
Wikiあたり見ても載ってないようなのですが
どこに載ってますか？？

**Comment by kanreisa** [comment]
@pick2 
忙しくて載せられていませんでした。ごめんなさい。
https://github.com/kanreisa/Chinachu/blob/master/node_modules/chinachu-common/lib/chinachu-common.js#L274-L327
こちらをご参照ください。
