### ISSUE TITLE
kodiのpvr.chinachuがstreamを受ける際エラーがでて受けられない

### ISSUE THREAD

**Issue by KitKuru** [Chinachu/Chinachu#278]
ログから何かわかりませんでしょうか

[log/wui]
18 Jun 19:13:09 - 405(!405) HEAD:/api/channel/GR_2080/watch.m2ts?ext=m2ts&c:v=copy&c:a=copy 192.168.1.102 "Kodi/16.1 (X11; Linux armv7l) OpenELEC/7.0 App_Bitness/32 Version/16.1-Git:c1c4b9e"
18 Jun 19:13:09 - LOCK: FSUSB2 (n=0)
18 Jun 19:13:09 - SPAWN: recfsusb2n -b 17 - - (pid=7442)
18 Jun 19:13:09 - #recfsusb2n: recfsusb2n ver. 0.9.2
18 Jun 19:13:09 - #recfsusb2n:
18 Jun 19:13:09 - #recfsusb2n: ISDB-T DTV Tuner FSUSB2N
18 Jun 19:13:09 - #recfsusb2n: device:
18 Jun 19:13:09 - #recfsusb2n: "
18 Jun 19:13:09 - #recfsusb2n: /
18 Jun 19:13:09 - #recfsusb2n: d
18 Jun 19:13:09 - #recfsusb2n: e
18 Jun 19:13:09 - #recfsusb2n: v
18 Jun 19:13:09 - #recfsusb2n: /bus/usb/003/002"
18 Jun 19:13:09 - #recfsusb2n: pid = 7442
18 Jun 19:13:10 - #recfsusb2n: B25Decoder initialized.
18 Jun 19:13:14 - 200 GET:/api/channel/GR_2080/watch.m2ts?ext=m2ts&c:v=copy&c:a=copy 192.168.1.102 "Kodi/16.1 (X11; Linux armv7l) OpenELEC/7.0 App_Bitness/32 Version/16.1-Git:c1c4b9e"
18 Jun 19:13:14 - WARNING: 利用可能なチューナーが見つかりません (存在しないかロックされています)
18 Jun 19:13:14 - 200(!500) GET:/api/channel/GR_2080/watch.m2ts?ext=m2ts&c:v=copy&c:a=copy 192.168.1.102 "Kodi/16.1 (X11; Linux armv7l) OpenELEC/7.0 App_Bitness/32 Version/16.1-Git:c1c4b9e"
[Error: Can't set headers after they are sent.]
18 Jun 19:13:15 - child process killing: PID=7442
18 Jun 19:13:15 - UNLOCK: FSUSB2 (n=0)
18 Jun 19:13:30 - 200 GET:/api/reserves.json 192.168.1.102 "Kodi/16.1 (X11; Linux armv7l) OpenELEC/7.0 App_Bitness/32 Version/16.1-Git:c1c4b9e"
18 Jun 19:14:12 - 405(!405) HEAD:/api/channel/GR_2088/watch.m2ts?ext=m2ts&c:v=copy&c:a=copy 192.168.1.102 "Kodi/16.1 (X11; Linux armv7l) OpenELEC/7.0 App_Bitness/32 Version/16.1-Git:c1c4b9e"
18 Jun 19:14:12 - LOCK: FSUSB2 (n=0)
[log/wui別パターン]
18 Jun 18:03:50 - 200 GET:/api/channel/GR_2088/watch.m2ts?ext=m2ts&c:v=copy&c:a=copy 192.168.1.102 "Kodi/16.1 (X11; Linux armv7l) OpenELEC/7.0 App_Bitness/32 Version/16.1-Git:c1c4b9e"
18 Jun 18:03:50 - WARNING: 利用可能なチューナーが見つかりません (存在しないかロックされています)

_http_outgoing.js:341
    throw new Error('Can\'t set headers after they are sent.');
    ^
18 Jun 18:03:50 - 200(!500) GET:/api/channel/GR_2088/watch.m2ts?ext=m2ts&c:v=copy&c:a=copy 192.168.1.102 "Kodi/16.1 (X11; Linux armv7l) OpenELEC/7.0 App_Bitness/32 Version/16.1-Git:c1c4b9e"
[Error: Can't set headers after they are sent.]
18 Jun 18:03:51 - child process killing: PID=32244

[kodi.log]
19:14:03 T:3035664384  NOTICE: DVDPlayer: Opening: pvr://channels/tv/全チャンネル/pvr.chinachu_2088.pvr
19:14:03 T:3035664384 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
19:14:03 T:2925511584  NOTICE: Creating InputStream
19:14:14 T:2925511584  NOTICE: Creating Demuxer
19:14:14 T:2925511584   ERROR: Open - error probing input format, pvr://channels/tv/全チャンネル/pvr.chinachu_2088.pvr
19:14:14 T:2925511584   ERROR: Previous line repeats 9 times.
19:14:14 T:2925511584   ERROR: OpenDemuxStream - Error creating demuxer
19:14:14 T:2925511584  NOTICE: CDVDPlayer::OnExit()
19:14:20 T:3035664384  NOTICE: CDVDPlayer::CloseFile()
19:14:20 T:3035664384  NOTICE: DVDPlayer: waiting for threads to exit
19:14:20 T:3035664384  NOTICE: DVDPlayer: finished waiting
19:14:20 T:3035664384  NOTICE: CDVDPlayer::CloseFile()
19:14:20 T:3035664384  NOTICE: DVDPlayer: waiting for threads to exit
19:14:20 T:3035664384  NOTICE: DVDPlayer: finished waiting
20:15:38 T:3035664384  NOTICE: DVDPlayer: Opening: pvr://channels/tv/全チャンネル/pvr.chinachu_2080.pvr
20:15:38 T:3035664384 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED

**Comment by mzyy94** [comment]
KodiのPVRアドオンの処理において、2つのリクエストがバックエンド側に渡ることがあるようです。そのため、視聴しようとしているチャンネルに対して2つのチューナーが必要になることがあります。
そのような場合、2つ以上のチューナーが非搭載であったり録画中で2つ以上のチューナーが確保できない場合に視聴ができないなどの状態となります。
詳しい原因は現在調査中で、状況が分かり次第アドオンでの対応もしくはKodi側への改修リクエストとなります。
主な原因としてはKodiの実装によるもので、Chinachu側で対応できることは多くないのでとりあえずこのIssueは開いたまま、議論に関しては
https://github.com/mzyy94/pvr.chinachu/issues/8
に移します。

**Comment by xxsl** [comment]
This two request is a http "HEAD" method  and a "GET" method, the contents are the same.
So change app-wui.js to this:

// Line 207
// HTTP Server
function httpServer(req, res) {

        var q = '';

        switch (req.method) {
        case 'HEAD':    // ignore HEAD
                break;
        case 'GET':

                q = url.parse(req.url, false).query || '';

problem solved but dirty. >~<

**Comment by mzyy94** [comment]
Oh, I see.
I found same problem last year while I was developing [Chinachu-IPTV-API-addon](https://github.com/mzyy94/Chinachu-IPTV-API-addon) (It's deprecated) and sent PR for changing HEAD  405 response code in #138.
Today, it's closed and not merged, so you should fix with @xxsl's way yourself, or try use [pvr.chinachu v3.1.0](https://github.com/Harekaze/pvr.chinachu/releases/tag/v3.1.0) with Mirakurun integration feature.

===== 

確かにそうでした。
昨年pvr.chinachuの前身であるChinachu-IPTV-API-addon（開発終了）を作っていた時にこの問題に直面してHEADリクエストの挙動を変更するプルリクを送っていました。
いろいろとあってマージはされず閉じたので、今日では@xxslさんのような修正をご自身で行っていただくか、[pvr.chinachu v3.1.0](https://github.com/Harekaze/pvr.chinachu/releases/tag/v3.1.0) のMirakurun経由で視聴する設定を有効にしてChinachu経由でのライブ視聴を回避する方法をとってみてください。
