### ISSUE TITLE
NHK BSプレミアムを録画するとウェザーニュースのデータも録画に含まれてしまう

### ISSUE THREAD

**Issue by midorigoke** [Chinachu/Chinachu#281]
タイトルの通りです。
BSプレミアムの全番組で発生するのではなく一部番組で発生しています。
それが発生する番組のコーデック情報を見ると
![](https://i.gyazo.com/a41d43252396f239656c23435fa38755.png)
![](https://i.gyazo.com/ffad22db1473076747cbfbc402052d9a.png)
(以下EPGデータが延々と続く)
このようになっているので、EPGのデータごと録画して何かが起きているのかと思います。
(詳しくないもので、すみません)
無変換でVLCを使い再生すると
![](https://i.gyazo.com/c8a312fd8eef39746e6c05dfd6f65a78.png)
プログラムの部分がこのようになります。
ここから一番上のプログラムを選べば本来録画した番組が見れます。
また、エンコードを通したストリーミング再生では問題なく本来の番組が見れます。
原因を特定していただけると有り難いです。

**Comment by mzyy94** [comment]
config.jsonのtunersの設定がどのようになっているかで問題解決への方向性が大きく変わってきます。
その部分の情報を見せていただくと解決の糸口がつかめるかもしれません。

**Comment by midorigoke** [comment]
tunersの設定はPT3用のサンプルをそのまま利用しています

**Comment by mzyy94** [comment]
その様子だとrecpt1の--stripオプションが効いていない（stripオプションがないrecpt1を使っている）、もしくはsidの指定がうまくいっていない可能性が高く、それが指定したサービスID以外のデータを取得しているようにも見えます。
そちらの環境を把握できていないので推測になってしまいますが、録画コマンドの確認やrecpt1の違う派生版に入れ替えてみることで原因の特定ができるのではないでしょうか

**Comment by midorigoke** [comment]
ありがとうございます。
試してみます。
