### ISSUE TITLE
chinachu-operatorが起動しない

### ISSUE THREAD

**Issue by 8350x** [Chinachu/Chinachu#282]
Debian 8を使用しています。

インストール後、

`$ sudo /etc/init.d/chinachu-operator start`
`$ sudo /etc/init.d/chinachu-wui start`

とすると
`Starting chinachu-operator: OK.`
`Starting chinachu-wui: OK.`

となるがwui上から見るとoperatorが停止している。wuiは起動できます。もちろん予約もできません。

ちなみに

`$ sudo service chinachu-operator start`

とすると

`Failed to start chinachu-operator.service: Unit chinachu-operator.service failed to load: No such file or directory.`

となります...。insservもちゃんとやったんですが...

`$ sudo systemctl restart chinachu-operator`

とかもやったのですが特にエラーは出ず、ただし動作しない...

**Comment by takaakis62** [comment]
insservの代わりにこれを試してみてください。
<pre>
$ sudo systemctl enable chinachu-operator
$ sudo systemctl enable chinachu-wui
</pre>

**Comment by 8350x** [comment]
回答有り難うございます。自己解決しました...。自分がやった作業のどれが解決になったのかわかりませんが、一応やったことを全て書きます。

・chinachuを一度消して、もう一度入れ直した。
・chmod -R 777をchinachuディレクトリに適用
・./chinachu updaterでupdateしたあと、自然に起動

とりあえずこれでoperatorもwuiも動作しました。まだすべての動作は確認できてませんので一応issuesは開けてさせてください。

**Comment by kanreisa** [comment]
起動時のログについて触れられてませんが何も出なかったんでしょうか？
chmod -R 777 はやめましょう。

**Comment by 8350x** [comment]
起動時のorepatorのログを見ると、起動できなかった時と全く同じでした。
`$ sudo /etc/init.d/chinachu-operator start`
`$ sudo /etc/init.d/chinachu-wui start`
ですんなり起動しました。

chmod -R 777から変えますが、chownでchinachuユーザーの所有にしてsudo使えさせるようにしてchmod 755とかでしょうか？

**Comment by RLambert142** [comment]
# cd /usr/local
# git clone git://github.com/kanreisa/Chinachu.git
# cd Chinachu/

# ./chinachu installer
what do you install? > 1

# echo "[]" > rules.json
# cp config.sample.json config.json

# ln -s /usr/local/Chinachu/chinachu /usr/bin/chinachu

# chinachu service operator execute
# chinachu service wui execute

# chinachu service operator initscript > /etc/init.d/chinachu-operator
# chinachu service wui initscript > /etc/init.d/chinachu-wui
# chmod 755 /etc/init.d/chinachu-operator
# chmod 755 /etc/init.d/chinachu-wui
# update-rc.d chinachu-operator defaults
# update-rc.d chinachu-wui defaults
# service chinachu-operator start
# service chinachu-wui start

私はこんな感じでインストールして普通に動作しています。

**Comment by haruo31** [comment]
かなり古い版から更新したら、同じ現象に遭いました。何もエラー出ませんね。

log/wui
`Client {
  basePath: '/api',
  priority: 0,
  host: '',
  port: 40772,
  socketPath: '/var/run/mirakurun.sock',
  userAgent: 'Chinachu/0.9.5-gamma.0 (wui)',
  _userAgent: 'MirakurunClient/2.0.0-rc.7 Node/v6.9.2 (linux)' }
**DEPRECATION WARNING**: please remove `wuiPort` and use `wuiOpenServer` instead.
info: socket.io started
info: socket.io started
(node:581) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:581) DeprecationWarning: sys is deprecated. Use util instead.
31 Dec 01:46:07 - HTTP Server Listening on { address: '::', family: 'IPv6', port: 10772 }
31 Dec 01:46:07 - HTTP Server mDNS advertising started.
31 Dec 01:46:07 - HTTP Open Server Listening on { address: '127.0.0.1', family: 'IPv4', port: 20772 }
31 Dec 01:46:07 - HTTP Open Server mDNS advertising started.
`

log/operator
`Client {
  basePath: '/api',
  priority: 2,
  host: '',
  port: 40772,
  socketPath: '/var/run/mirakurun.sock',
  userAgent: 'Chinachu/0.9.5-gamma.0 (operator)',
  _userAgent: 'MirakurunClient/2.0.0-rc.7 Node/v6.9.2 (linux)' }
31 Dec 01:48:12 - READ: `/home/chinachu/chinachu/data/reserves.json` is updated.
31 Dec 01:48:12 - READ: `/home/chinachu/chinachu/data/recorded.json` is updated.
31 Dec 01:48:18 - SPAWN: node app-scheduler.js (pid=765)
31 Dec 01:48:18 - STREAM: ./log/scheduler
31 Dec 01:48:18 - EXIT: node app-scheduler.js (pid=765)
31 Dec 01:48:19 - READ: `/home/chinachu/chinachu/data/reserves.json` is updated.
31 Dec 01:58:18 - SPAWN: node app-scheduler.js (pid=786)
31 Dec 01:58:18 - STREAM: ./log/scheduler
31 Dec 01:58:19 - EXIT: node app-scheduler.js (pid=786)
31 Dec 01:58:20 - READ: `/home/chinachu/chinachu/data/reserves.json` is updated.
`

log/scheduler
`Client {
  basePath: '/api',
  priority: 0,
  host: '',
  port: 40772,
  socketPath: '/var/run/mirakurun.sock',
  userAgent: 'Chinachu/0.9.5-gamma.0 (scheduler)',
  _userAgent: 'MirakurunClient/2.0.0-rc.7 Node/v6.9.2 (linux)' }
31 Dec 01:58:19 - GETTING EPG from Mirakurun.
31 Dec 01:58:19 - Mirakurun is OK.
31 Dec 01:58:19 - Mirakurun -> services: 0
31 Dec 01:58:19 - Mirakurun -> programs: 0
31 Dec 01:58:19 - Mirakurun -> tuners: 0
31 Dec 01:58:19 - WRITE: /home/chinachu/chinachu/data/schedule.json
31 Dec 01:58:19 - RUNNING SCHEDULER.
31 Dec 01:58:19 - TUNERS: {}
31 Dec 01:58:19 - MATCHES: 0
31 Dec 01:58:19 - DUPLICATES: 0
31 Dec 01:58:19 - CONFLICTS: 0
31 Dec 01:58:19 - SKIPS: 0
31 Dec 01:58:19 - RESERVES: 0
31 Dec 01:58:19 - WRITE: /home/chinachu/chinachu/data/reserves.json
`

**Comment by kanreisa** [comment]
@haruo31
すいませんがどの辺が同じ現象なのかわかりません。もう一度issue立てていただければと思います。
