### ISSUE TITLE
gamma にはルール予約の設定に曜日指定は出来ないの？

### ISSUE THREAD

**Issue by neologin2** [Chinachu/Chinachu#296]
gamma にはルール予約の設定に曜日指定は出来ないのでしょうか？
また、番組表の表示される順番を変更したくてconfig.jsonやchannels.ymlの順番をイジってみましたが
全く変更される様子がありません。変更する方法ありましたら教えてください。

**Comment by neologin2** [comment]
ルール設定のところで対象チャンネルを指定してると録画予約出来てないことに気づきました。
以前は、GR_xxxx って感じになっていたのに
gannmaからは、1i4d2rs となっているせいだと思うのですがこの数字はどうやって決まっているのでしょうか？

**Comment by neologin2** [comment]
ルール設定のところで対象チャンネルを指定してると録画予約出来てないことに気づきました。
以前は、GR_xxxx って感じになっていたのに
gammaからは、1i4d2rs となっているせいだと思うのですがこの数字はどうやって決まっているのでしょうか？

**Comment by kanreisa** [comment]
> gamma にはルール予約の設定に曜日指定は出来ないのでしょうか？
今のところは、できません。
https://github.com/Chinachu/Chinachu/issues/284

> 番組表の表示される順番を変更
これも今のところはできない仕様となっています m(_ _)m
