### ISSUE TITLE
gammaでなぜか録画できずエラー

### ISSUE THREAD

**Issue by ohatsu** [Chinachu/Chinachu#298]
![capture 013](https://cloud.githubusercontent.com/assets/24849928/21575733/d7fefb8a-cf59-11e6-9124-91316e83d865.jpg)
録画中にこのようなエラーが永遠と表示され録画出来ておりませんでした。
以下ログです。

31 Dec 12:57:09 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:57:09 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:57:09 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:57:15 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:57:15 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:57:15 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:57:21 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:57:21 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:57:21 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:57:27 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:57:27 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:57:27 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:57:33 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:57:33 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:57:33 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:57:39 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:57:39 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:57:39 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:57:45 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:57:45 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:57:45 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:57:51 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:57:51 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:57:51 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:57:57 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:57:57 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:57:57 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:58:03 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:58:03 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:58:03 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:58:09 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:58:09 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:58:09 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:58:15 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:58:15 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:58:15 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:58:21 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:58:21 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:58:21 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:58:27 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:58:27 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:58:27 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:58:33 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:58:33 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:58:33 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:58:39 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:58:39 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:58:39 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:58:45 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:58:45 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:58:45 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:58:51 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:58:51 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:58:51 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:58:57 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:58:57 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:58:57 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:59:03 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:59:03 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:59:03 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:59:09 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:59:09 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:59:09 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:59:15 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:59:15 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:59:15 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:59:21 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:59:21 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:59:21 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:59:27 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:59:27 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:59:27 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:59:33 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:59:33 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:59:33 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:59:39 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:59:39 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:59:39 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:59:45 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:59:45 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:59:45 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:59:51 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:59:51 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:59:51 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 12:59:54 - SPAWN: node app-scheduler.js (pid=11088)
31 Dec 12:59:54 - STREAM: ./log/scheduler
31 Dec 12:59:55 - EXIT: node app-scheduler.js (pid=11088)
31 Dec 12:59:56 - READ: `/usr/local/Chinachu/data/reserves.json` is updated.
31 Dec 12:59:56 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:59:57 - PREPARE: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:59:57 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 12:59:57 - ERROR: #gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会 /api/programs/36467962568/stream 404 Not Found
31 Dec 13:00:00 - WRITE: /usr/local/Chinachu/data/recorded.json
31 Dec 13:00:00 - WRITE: /usr/local/Chinachu/data/recording.json
31 Dec 13:00:00 - WRITE: /usr/local/Chinachu/data/reserves.json
31 Dec 13:00:00 - SPAWN: /usr/local/Chinachu/recorded-command (pid=11100)
31 Dec 13:00:00 - FIN: #w68gfcf 2016-12-31T12:30:00+0900 [ディスカバリー] クラシックカー・コレクション：フェラーリ365Pベルリネッタ(二)
31 Dec 13:00:01 - READ: `/usr/local/Chinachu/data/recorded.json` is updated.
31 Dec 13:00:01 - READ: `/usr/local/Chinachu/data/reserves.json` is updated.
31 Dec 13:00:01 - WRITE: /usr/local/Chinachu/data/recording.json

31 Dec 12:29:49 - !!!SKIP: iduguze 2017-01-02T18:45:00+0900 [ＷＯＷＯＷシネマ] ターミネーター（字幕版）[PG12指定][SS]
31 Dec 12:29:49 - RESERVE: w68gfgj 2017-01-03T20:00:00+0900 [ディスカバリー] ゴールドラッシュ人生最後の一攫千金S3：Ep.10 ブルドーザー戦争(二)
31 Dec 12:29:49 - !!!SKIP: iduw4lo 2017-01-07T11:00:00+0900 [スターチャンネル１] [SS]ターミネーター
31 Dec 12:29:49 - !!!SKIP: idy04u7 2017-01-07T21:00:00+0900 [イマジカＢＳ・映画] .1】ターミネーター4
31 Dec 12:29:49 - MATCHES: 8
31 Dec 12:29:49 - DUPLICATES: 0
31 Dec 12:29:49 - CONFLICTS: 0
31 Dec 12:29:49 - SKIPS: 3
31 Dec 12:29:49 - RESERVES: 5
31 Dec 12:29:49 - WRITE: /usr/local/Chinachu/data/reserves.json
Client {
basePath: '/api',
priority: 0,
host: '',
port: 40772,
socketPath: '/var/run/mirakurun.sock',
userAgent: 'Chinachu/0.9.5-gamma.0 (scheduler)',
_userAgent: 'MirakurunClient/2.0.0-rc.7 Node/v6.9.2 (linux)' }
31 Dec 12:39:48 - GETTING EPG from Mirakurun.
31 Dec 12:39:48 - Mirakurun is OK.
31 Dec 12:39:48 - Mirakurun -> services: 63
31 Dec 12:39:48 - Mirakurun -> programs: 11431
31 Dec 12:39:49 - Mirakurun -> tuners: 4
31 Dec 12:39:49 - WRITE: /usr/local/Chinachu/data/schedule.json
31 Dec 12:39:49 - RUNNING SCHEDULER.
31 Dec 12:39:49 - TUNERS: {"BS":2,"CS":2,"GR":2}
31 Dec 12:39:49 - RESERVE: w68gfcf 2016-12-31T12:30:00+0900 [ディスカバリー] クラシックカー・コレクション：フェラーリ365Pベルリネッタ(二)
31 Dec 12:39:49 - RESERVE: gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:39:49 - RESERVE: 3800o4zmhx 2017-01-01T18:00:00+0900 [読売テレビ１] 元日はＴＯＫＩＯ×嵐　ウルトラマンＤＡＳＨ
31 Dec 12:39:49 - RESERVE: 37zrhcjhgq 2017-01-01T18:00:00+0900 [ＡＢＣテレビ１] 芸能人格付けチェック！これぞ真の一流品だ！２０１７お正月ＳＰ連勝ガクトに刺客
31 Dec 12:39:49 - !!!SKIP: iduguze 2017-01-02T18:45:00+0900 [ＷＯＷＯＷシネマ] ターミネーター（字幕版）[PG12指定][SS]
31 Dec 12:39:49 - RESERVE: w68gfgj 2017-01-03T20:00:00+0900 [ディスカバリー] ゴールドラッシュ人生最後の一攫千金S3：Ep.10 ブルドーザー戦争(二)
31 Dec 12:39:49 - !!!SKIP: iduw4lo 2017-01-07T11:00:00+0900 [スターチャンネル１] [SS]ターミネーター
31 Dec 12:39:49 - !!!SKIP: idy04u7 2017-01-07T21:00:00+0900 [イマジカＢＳ・映画] .1】ターミネーター4
31 Dec 12:39:49 - MATCHES: 8
31 Dec 12:39:49 - DUPLICATES: 0
31 Dec 12:39:49 - CONFLICTS: 0
31 Dec 12:39:49 - SKIPS: 3
31 Dec 12:39:49 - RESERVES: 5
31 Dec 12:39:49 - WRITE: /usr/local/Chinachu/data/reserves.json
Client {
basePath: '/api',
priority: 0,
host: '',
port: 40772,
socketPath: '/var/run/mirakurun.sock',
userAgent: 'Chinachu/0.9.5-gamma.0 (scheduler)',
_userAgent: 'MirakurunClient/2.0.0-rc.7 Node/v6.9.2 (linux)' }
31 Dec 12:49:48 - GETTING EPG from Mirakurun.
31 Dec 12:49:48 - Mirakurun is OK.
31 Dec 12:49:48 - Mirakurun -> services: 63
31 Dec 12:49:48 - Mirakurun -> programs: 11431
31 Dec 12:49:49 - Mirakurun -> tuners: 4
31 Dec 12:49:49 - WRITE: /usr/local/Chinachu/data/schedule.json
31 Dec 12:49:49 - RUNNING SCHEDULER.
31 Dec 12:49:49 - TUNERS: {"BS":2,"CS":2,"GR":2}
31 Dec 12:49:49 - RESERVE: w68gfcf 2016-12-31T12:30:00+0900 [ディスカバリー] クラシックカー・コレクション：フェラーリ365Pベルリネッタ(二)
31 Dec 12:49:49 - RESERVE: gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:49:49 - RESERVE: 3800o4zmhx 2017-01-01T18:00:00+0900 [読売テレビ１] 元日はＴＯＫＩＯ×嵐　ウルトラマンＤＡＳＨ
31 Dec 12:49:49 - RESERVE: 37zrhcjhgq 2017-01-01T18:00:00+0900 [ＡＢＣテレビ１] 芸能人格付けチェック！これぞ真の一流品だ！２０１７お正月ＳＰ連勝ガクトに刺客
31 Dec 12:49:49 - !!!SKIP: iduguze 2017-01-02T18:45:00+0900 [ＷＯＷＯＷシネマ] ターミネーター（字幕版）[PG12指定][SS]
31 Dec 12:49:49 - RESERVE: w68gfgj 2017-01-03T20:00:00+0900 [ディスカバリー] ゴールドラッシュ人生最後の一攫千金S3：Ep.10 ブルドーザー戦争(二)
31 Dec 12:49:49 - !!!SKIP: iduw4lo 2017-01-07T11:00:00+0900 [スターチャンネル１] [SS]ターミネーター
31 Dec 12:49:49 - !!!SKIP: idy04u7 2017-01-07T21:00:00+0900 [イマジカＢＳ・映画] .1】ターミネーター4
31 Dec 12:49:49 - MATCHES: 8
31 Dec 12:49:49 - DUPLICATES: 0
31 Dec 12:49:49 - CONFLICTS: 0
31 Dec 12:49:49 - SKIPS: 3
31 Dec 12:49:49 - RESERVES: 5
31 Dec 12:49:49 - WRITE: /usr/local/Chinachu/data/reserves.json
Client {
basePath: '/api',
priority: 0,
host: '',
port: 40772,
socketPath: '/var/run/mirakurun.sock',
userAgent: 'Chinachu/0.9.5-gamma.0 (scheduler)',
_userAgent: 'MirakurunClient/2.0.0-rc.7 Node/v6.9.2 (linux)' }
31 Dec 12:59:54 - GETTING EPG from Mirakurun.
31 Dec 12:59:54 - Mirakurun is OK.
31 Dec 12:59:54 - Mirakurun -> services: 63
31 Dec 12:59:54 - Mirakurun -> programs: 11435
31 Dec 12:59:55 - Mirakurun -> tuners: 4
31 Dec 12:59:55 - WRITE: /usr/local/Chinachu/data/schedule.json
31 Dec 12:59:55 - RUNNING SCHEDULER.
31 Dec 12:59:55 - TUNERS: {"BS":2,"CS":2,"GR":2}
31 Dec 12:59:55 - RESERVE: w68gfcf 2016-12-31T12:30:00+0900 [ディスカバリー] クラシックカー・コレクション：フェラーリ365Pベルリネッタ(二)
31 Dec 12:59:55 - RESERVE: gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会
31 Dec 12:59:55 - RESERVE: 3800o4zmhx 2017-01-01T18:00:00+0900 [読売テレビ１] 元日はＴＯＫＩＯ×嵐　ウルトラマンＤＡＳＨ
31 Dec 12:59:55 - RESERVE: 37zrhcjhgq 2017-01-01T18:00:00+0900 [ＡＢＣテレビ１] 芸能人格付けチェック！これぞ真の一流品だ！２０１７お正月ＳＰ連勝ガクトに刺客
31 Dec 12:59:55 - !!!SKIP: iduguze 2017-01-02T18:45:00+0900 [ＷＯＷＯＷシネマ] ターミネーター（字幕版）[PG12指定][SS]
31 Dec 12:59:55 - RESERVE: w68gfgj 2017-01-03T20:00:00+0900 [ディスカバリー] ゴールドラッシュ人生最後の一攫千金S3：Ep.10 ブルドーザー戦争(二)
31 Dec 12:59:55 - !!!SKIP: iduw4lo 2017-01-07T11:00:00+0900 [スターチャンネル１] [SS]ターミネーター
31 Dec 12:59:55 - !!!SKIP: idy04u7 2017-01-07T21:00:00+0900 [イマジカＢＳ・映画] .1】ターミネーター4
31 Dec 12:59:55 - MATCHES: 8
31 Dec 12:59:55 - DUPLICATES: 0
31 Dec 12:59:55 - CONFLICTS: 0
31 Dec 12:59:55 - SKIPS: 3
31 Dec 12:59:55 - RESERVES: 5
31 Dec 12:59:55 - WRITE: /usr/local/Chinachu/data/reserves.json

**Comment by ohatsu** [comment]
あと、新規ルールで対象CHを指定しようと思ったのですが
以前のバージョンと指定方法が変わっているようでよくわかりません。
同じ放送局でも番組毎にチャンネル番号が違うような感じがします。

**Comment by ohatsu** [comment]
![capture 014](https://cloud.githubusercontent.com/assets/24849928/21575745/8876e91e-cf5a-11e6-8201-a2668f838c0b.jpg)

あと、新規ルールで対象CHを指定しようと思ったのですが
以前のバージョンと指定方法が変わっているようでよくわかりません。
同じ放送局でも番組毎にチャンネル番号が違うような感じがします。

**Comment by ohatsu** [comment]
![capture 015](https://cloud.githubusercontent.com/assets/24849928/21575753/f14e844c-cf5a-11e6-8aae-8b31bb7c2338.jpg)

gammaからチャンネル指定方法が変わったのでしょうか？
どの放送局がどのチャンネルかよくわかりません。

**Comment by kanreisa** [comment]
番組IDおよびチャンネルIDの仕様が変更になりました。

したがって、

> 31 Dec 12:39:49 - RESERVE: gr43008-fnv 2016-12-31T12:45:00+0900 [ＮＨＫ総合１・神戸] 全国自治宝くじ　年末ジャンボ抽せん会

`gr43008-fnv` この番組は古い仕様のため、録画できません。放置しておけば正常化すると思いますが、不安でしたら一旦 `/data/reserves.json` を削除して再起動してください。

また、チャンネル指定方法は ID または物理チャンネルで指定可能ですので、 `23` 等でも可能です。
IDに関してはもともと覚えやすいようなものでも無かったかと思います。

**Comment by tosono** [comment]
横から失礼します。
Mirakurun側で以下の様にＣＳをトラポン単位で丸ごと指定していると、
チャンネル指定でどれがどのチャンネルなのか、分からなくなってしまうので、
Chinachu側で手が打てればうれしいのですが。。。

```
- name: ND2
  type: CS
  channel: CS2
  isDisabled: false

- name: ND4
  type: CS
  channel: CS4
  isDisabled: false
```

また、Mirakurunのサンプルconfigも以下の様になってたりしますが、
両方有効にした場合、chinachu側のチャンネルは全部`CS2`が複数出てきて、
どれがどのチャンネルなのか分からなくなってしまうのでは無いでしょうか・・・

```
- name: TV Asahi Ch. 1
  type: CS
  channel: CS2
  serviceId: 298
  isDisabled: true

- name: TV Asahi Ch. 2
  type: CS
  channel: CS2
  serviceId: 299
  isDisabled: true
```
`serviceId`が有れば、`channel`はコメント扱いで良かったんでしたっけ？
で有れば、`channel`を好きなように振れるのでなんとかなりますけど。
だったとしても、Mirakurunでトラポン単位で設定していると、どうにもならない事には、変わりないんですけどね。

Chinachu側で`type + serviceId`か、`name`でチャンネル扱えるようになればと、ソース眺めてるんですが、
ん～って感じです。
まぁ、手抜きせず、Mirakurunのchannels設定真面目にやれって話しなのかもしれませんが（苦笑

**Comment by kanreisa** [comment]
オススメなのは番組ページからのルール作成なのですが、チャンネル選択に関するUIはAirで何とかなる予定ですのでもう少しご辛抱を。

`channel` は必須で、コメント扱いではありません m(_ _)m

**Comment by tosono** [comment]
回答ありがとうございます。
現状、チャンネル指定のルールが多くないので、id調べて、頑張って36進変換して指定しました（笑
当面これでガンバリマス。

Airでの対応、楽しみにしています。

**Comment by kanreisa** [comment]
トップのチャンネルリストからチャンネルを表示して、URLを見るとIDが見えます
