### ISSUE TITLE
チャンネルの順番

### ISSUE THREAD

**Issue by inoueiine** [Chinachu/Chinachu#304]
久々のアップデートに期待してγにアップデートしました
アップデート後、少し気になったのですが番組表の順番が変更出来ないようになっており不便です
リモコンの順番と一緒に並び替えたいです
あと、ルールに曜日の指定が出来るようになって欲しいです

**Comment by kanreisa** [comment]
一般のテレビやTVTestを見ても変更できないケースが大半だと思うのですが、
どういったところが不便でしょうか？
必要に応じて番組表設定もご活用いただければ幸いです。

曜日の件はこちら
https://github.com/Chinachu/Chinachu/issues/284

**Comment by neologin2** [comment]
私も番組表の並び替えほしいですね
放送局名で覚えてるのではなく、1ch、2chとかで覚えてるのでその順番に修正したいと私は思っています。
あと、CSとかで複数回放送してるような番組表をルールで指定する場合に曜日があれば
無駄な容量を食わなくて済みます。

**Comment by inoueiine** [comment]
kanreisaさんへ
私もテレビのチャンネルの番号で覚えている為、順番が違うと番組を探したりするのに
手こずるので表示順番が変更出来るようにしてほしいのです。
曜日の件は対応する予定が無いので残念です。CSだと一週間に同じ番組が５回前後してたことが
あったのでその都度キャンセルするのがとてもめんどくさいので曜日設定が欲しいのです。

**Comment by kanreisa** [comment]
いろいろ検討しているのでしばらくお待ちいただけますか。

曜日の件はこちらなので、あんまり議論を混ぜないでいただけると幸いです。
https://github.com/Chinachu/Chinachu/issues/284

**Comment by kanreisa** [comment]
@inoueiine @neologin2 
mirakurun@2.0.0 でリモコンキーID順に並ぶようになりました。
ご確認のほどよろしくお願いいたします。

**Comment by kanreisa** [comment]
最新版にてリモコンキーID順に正しく表示されないバグを修正しました

**Comment by tora3** [comment]
remoteControlKeyId の設定方法（サンプル）を教えてください。

**Comment by kanreisa** [comment]
設定することはできないのです
https://ja.wikipedia.org/wiki/%E3%83%AA%E3%83%A2%E3%82%B3%E3%83%B3%E3%82%AD%E3%83%BCID

**Comment by tora3** [comment]
ユーザが好きな順番に表示順を並べ替える事は出来ないのですね。:-(

**Comment by kanreisa** [comment]
できます。
https://github.com/Chinachu/Chinachu/wiki/Gamma-Configuration#configjson
serviceOrder で ServiceItemID を指定して並び順を変更できます。

**Comment by tora3** [comment]
出来ました。ありがとうございます。

あけましておめでとうございます。
