### ISSUE TITLE
ディスクフル時の挙動について

### ISSUE THREAD

**Issue by hendecarows** [Chinachu/Chinachu#306]
Ubuntu 16.04 で chinachu γ (βからUpdate) を使っています。
システムと録画ファイルは同じ１つのHDDで config.json に以下を指定しています。
rootの予約領域は確保してます(デフォルトから変更していません)。

"storageLowSpaceThresholdMB": 5000,
"storageLowSpaceAction": "remove",

録画に失敗していたので operator ログを確認した所以下のエラーが出力されていました。
HDD容量が足りなくて書き込めなかったようです。

uncaughtException: Error: ENOSPC: no space left on device, write
    at Error (native)
    at Object.fs.writeSync (fs.js:786:20)
    at Object.fs.writeFileSync (fs.js:1343:24)
...

https://github.com/Chinachu/Chinachu/blob/gamma/app-operator.js#L474
の出力を探しましたがありませんでした。

不要なファイルを削除する前の値を出力するのを忘れたため削除した後の値ですが、

$ df --block-size=1
Filesystem        1B-blocks         Used    Available Use% Mounted on
/dev/sda1      980261949440 504754741248 425689206784  55% /

https://www.npmjs.com/package/diskusage
のサンプルコードを実行した結果

425689206784  // info.available
475507208192  // info.free
980261949440  // info.total

https://github.com/Chinachu/Chinachu/blob/gamma/app-operator.js#L471

正直な所良く分かっていませんが info.free を info.available に変えて
あげれば良さそうな気がしているのですがどうなんでしょうか？

**Comment by kanreisa** [comment]
ご指摘いただきありがとうございます。
修正してみます。

**Comment by takaakis62** [comment]
info.freeには予約領域を含むため、storageLowSpaceThresholdMBを予約領域より大きくしないとディスクフルで書き込めなくなっても何も動作しません。
予約領域を含まないinfo.availableにすることで、ディスクフルで書き込めなくなる前に設定した処理が動作することを確認しました。
```
7 Feb 18:45:04 - ALERT: Storage Low Space! (0 MB < 30000 MB)
7 Feb 18:45:04 - WRITE: /home/user/chinachu/data/recorded.json
7 Feb 18:45:06 - READ: `/home/user/chinachu/data/recorded.json` is updated.
7 Feb 18:45:28 - ALERT: Storage Low Space! (0 MB < 30000 MB)
7 Feb 18:45:29 - WRITE: /home/user/chinachu/data/recorded.json
7 Feb 18:45:30 - READ: `/home/user/chinachu/data/recorded.json` is updated.
7 Feb 18:45:53 - ALERT: Storage Low Space! (0 MB < 30000 MB)
7 Feb 18:45:53 - WRITE: /home/user/chinachu/data/recorded.json
7 Feb 18:45:54 - READ: `/home/user/chinachu/data/recorded.json` is updated.
7 Feb 18:46:17 - ALERT: Storage Low Space! (0 MB < 30000 MB)
7 Feb 18:46:17 - WRITE: /home/user/chinachu/data/recorded.json
7 Feb 18:46:18 - READ: `/home/user/chinachu/data/recorded.json` is updated.
7 Feb 18:46:41 - ALERT: Storage Low Space! (0 MB < 30000 MB)
7 Feb 18:46:41 - WRITE: /home/user/chinachu/data/recorded.json
7 Feb 18:46:42 - READ: `/home/user/chinachu/data/recorded.json` is updated.
7 Feb 18:47:05 - ALERT: Storage Low Space! (0 MB < 30000 MB)
7 Feb 18:47:05 - WRITE: /home/user/chinachu/data/recorded.json
7 Feb 18:47:06 - READ: `/home/user/chinachu/data/recorded.json` is updated.
7 Feb 18:47:29 - ALERT: Storage Low Space! (1803.98828125 MB < 30000 MB)
7 Feb 18:47:29 - WRITE: /home/user/chinachu/data/recorded.json
7 Feb 18:47:31 - READ: `/home/user/chinachu/data/recorded.json` is updated.
```
