### ISSUE TITLE
DLNAについて

### ISSUE THREAD

**Issue by DABURUTTI** [Chinachu/Chinachu#309]
DLNAの番組一覧が更新されません...
再起動するとリストが更新され、録画した内容が表示されるようになります。
これは仕様なのでしょうか？

**Comment by kanreisa** [comment]
Chinachu のバージョンと、クライアントも教えていただけるとありがたいです。
クライアント側で一覧がキャッシュされている事が原因かと思います。

**Comment by DABURUTTI** [comment]
Chinachuは最新（1.3.0）です、クライアントはKodiやandroidのアプリBubbleUPnP等です...！

**Comment by kanreisa** [comment]
のちほど詳しく確認してみます ⏳

**Comment by DABURUTTI** [comment]
解決しました!
お騒がせしてすいません... 
今後ともよろしくお願いします!
