### ISSUE TITLE
ルール指定に曜日が指定出来ないのはなぜ？

### ISSUE THREAD

**Issue by slogjanb** [Chinachu/Chinachu#311]
要望に何件かあがってるようなのですが、私もルールに曜日指定が出来るようにして欲しい一人です。
例えば、海外ドラマ等を録画してる人はどうしてるのでしょうか？
一週間にこんなにも同じドラマが繰り返し方法されてるので、何度も録画されて困ってます。
![capture 015](https://cloud.githubusercontent.com/assets/25561475/22624525/b59940bc-ebc1-11e6-9acf-522769b6891d.jpg)

**Comment by kanreisa** [comment]
貴重なご意見ありがとうございます。現状では時間指定を活用していただくと良いのかなと思います。

※重複していますのでこの件は今後はこちらでお願いいたします→ https://github.com/Chinachu/Chinachu/issues/284
