### ISSUE TITLE
chinachu gamma と Mirakurun のアップデート

### ISSUE THREAD

**Issue by neologin2** [Chinachu/Chinachu#314]
ネットで検索すると色々と方法があるみたいですが
公式サイト的にはどういうコマンドでのアップデートを推奨しているのでしょうか？

**Comment by kanreisa** [comment]
ネットで検索するまでもなく
* https://github.com/Chinachu/Chinachu/wiki/How-to-Update
* https://github.com/Chinachu/Mirakurun/blob/master/README.md#update
に書いてありますよ
