### ISSUE TITLE
nodeインストールの一部が失敗する

### ISSUE THREAD

**Issue by jrtakahiro** [Chinachu/Chinachu#318]
`nvm install` でnode v6.9.5を導入済みで、
mirakurunとrivarunは無事動いてますが、
　
`./chinachu installer` を実行すると以下のようになりnodeの一部が失敗しました。
　
Chinachu Installer Menu:
[!] These are installed under all /home/chinachu/chinachu/...
[!] Recommend the Auto installation.
1) Auto (full)		3) Node.js Environment	5) ffmpeg
2) submodule		4) Node.js Modules
what do you install? > 1
selected: Auto (full)
removed `/home/chinachu/chinachu/.nave'
Installing Node using Nave...
--2017-03-21 14:01:21--  https://github.com/isaacs/nave/archive/v0.5.1.tar.gz
Resolving github.com (github.com)... 192.30.255.112, 192.30.255.113
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/isaacs/nave/tar.gz/v0.5.1 [following]
--2017-03-21 14:01:22--  https://codeload.github.com/isaacs/nave/tar.gz/v0.5.1
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘STDOUT’

-                                  [ <=>                                                 ]   7.46K  --.-KB/s   in 0.002s 

2017-03-21 14:01:23 (3.91 MB/s) - written to stdout [7640]

nave-0.5.1/nave.sh
removed directory: ‘/home/chinachu/chinachu/.nave/nave-0.5.1’

curl: (22) The requested URL returned error: 404 Not Found
######################################################################## 100.0%
curl: (22) The requested URL returned error: 404 Not Found
Binary download failed, trying source.

curl: (22) The requested URL returned error: 404 Not Found
######################################################################## 100.0%
fetched from http://nodejs.org/dist/v6.9.2/node-v6.9.2.tar.gz
/home/chinachu/chinachu/.nave/nave.sh: line 292: sysctl: command not found
creating  ./icu_config.gypi
* Using ICU in deps/icu-small
creating  ./icu_config.gypi
{ 'target_defaults': { 'cflags': [],
                       'default_configuration': 'Release',
                       'defines': [],
                       'include_dirs': [],
                       'libraries': []},
  'variables': { 'asan': 0,
                 'debug_devtools': 'node',
                 'force_dynamic_crt': 0,
                 'gas_version': '2.25',
                 'host_arch': 'arm64',
                 'icu_data_file': 'icudt57l.dat',
                 'icu_data_in': '../../deps/icu-small/source/data/in/icudt57l.dat',
                 'icu_endianness': 'l',
                 'icu_gyp_path': 'tools/icu/icu-generic.gyp',
                 'icu_locales': 'en,root',
                 'icu_path': 'deps/icu-small',
                 'icu_small': 'true',
                 'icu_ver_major': '57',
                 'node_byteorder': 'little',
                 'node_enable_d8': 'false',
                 'node_enable_v8_vtunejit': 'false',
                 'node_install_npm': 'true',
                 'node_module_version': 48,
                 'node_no_browser_globals': 'false',
                 'node_prefix': '/home/chinachu/chinachu/.nave/installed/6.9.2',
                 'node_release_urlbase': '',
                 'node_shared': 'false',
                 'node_shared_cares': 'false',
                 'node_shared_http_parser': 'false',
                 'node_shared_libuv': 'false',
                 'node_shared_openssl': 'false',
                 'node_shared_zlib': 'false',
                 'node_tag': '',
                 'node_use_bundled_v8': 'true',
                 'node_use_dtrace': 'false',
                 'node_use_etw': 'false',
                 'node_use_lttng': 'false',
                 'node_use_openssl': 'true',
                 'node_use_perfctr': 'false',
                 'node_use_v8_platform': 'true',
                 'openssl_fips': '',
                 'openssl_no_asm': 0,
                 'shlib_suffix': 'so.48',
                 'target_arch': 'arm64',
                 'uv_parent_path': '/deps/uv/',
                 'uv_use_dtrace': 'false',
                 'v8_enable_gdbjit': 0,
                 'v8_enable_i18n_support': 1,
                 'v8_inspector': 'true',
                 'v8_no_strict_aliasing': 1,
                 'v8_optimized_debug': 0,
                 'v8_random_seed': 0,
                 'v8_use_snapshot': 'true',
                 'want_separate_host_toolset': 0}}
creating  ./config.gypi
creating  ./config.mk
make -C out BUILDTYPE=Release V=1
make[1]: Entering directory '/home/chinachu/chinachu/.nave/src/6.9.2/out'
  g++  -I../deps/gtest -I../deps/gtest/include  -pthread -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /home/chinachu/chinachu/.nave/src/6.9.2/out/Release/.deps//home/chinachu/chinachu/.nave/src/6.9.2/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o.d.raw  -O2 -w -pipe -march=native -c -o /home/chinachu/chinachu/.nave/src/6.9.2/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o ../deps/gtest/src/gtest-death-test.cc
  g++  -I../deps/gtest -I../deps/gtest/include  -pthread -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /home/chinachu/chinachu/.nave/src/6.9.2/out/Release/.deps//home/chinachu/chinachu/.nave/src/6.9.2/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o.d.raw  -O2 -w -pipe -march=native -c -o /home/chinachu/chinachu/.nave/src/6.9.2/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o ../deps/gtest/src/gtest-filepath.cc
Assembler messages:
Error: unknown architecture `native'

Error: unrecognized option -march=native
Assembler messages:
Error: unknown architecture `native'

Error: unrecognized option -march=native
../deps/gtest/src/gtest-death-test.cc:1:0: error: unknown value ‘native’ for -march
 // Copyright 2005, Google Inc.
 ^
../deps/gtest/src/gtest-filepath.cc:1:0: error: unknown value ‘native’ for -march
 // Copyright 2008, Google Inc.
 ^
deps/gtest/gtest.target.mk:79: recipe for target '/home/chinachu/chinachu/.nave/src/6.9.2/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o' failed
make[1]: *** [/home/chinachu/chinachu/.nave/src/6.9.2/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o] Error 1
make[1]: *** Waiting for unfinished jobs....
deps/gtest/gtest.target.mk:79: recipe for target '/home/chinachu/chinachu/.nave/src/6.9.2/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o' failed
make[1]: *** [/home/chinachu/chinachu/.nave/src/6.9.2/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o] Error 1
make[1]: Leaving directory '/home/chinachu/chinachu/.nave/src/6.9.2/out'
Makefile:68: recipe for target 'node' failed
make: *** [node] Error 2
Failed to make 6.9.2
fail
‘/home/chinachu/chinachu/.nave/node’ -> ‘/home/chinachu/chinachu/.nave/installed/6.9.2/bin/node’
‘/home/chinachu/chinachu/.nave/npm’ -> ‘/home/chinachu/chinachu/.nave/installed/6.9.2/bin/npm’
done.
Installing Node Modules using NPM...

> ffi@2.2.0 install /home/chinachu/chinachu/node_modules/ffi
> node-gyp rebuild

make: Entering directory '/home/chinachu/chinachu/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
Assembler messages:
Error: unknown architecture `native'

Error: unrecognized option -march=native
Assembler messages:
Error: unknown architecture `native'

Error: unrecognized option -march=native
Assembler messages:
Error: unknown architecture `native'

Error: unrecognized option -march=native
Assembler messages:
Error: unknown architecture `native'

Error: unrecognized option -march=native
Assembler messages:
Error: unknown architecture `native'

Error: unrecognized option -march=native
../deps/libffi/src/prep_cif.c:1:0: error: unknown value ‘native’ for -march
 /* -----------------------------------------------------------------------
 ^
../deps/libffi/src/java_raw_api.c:1:0: error: unknown value ‘native’ for -march
 /* -----------------------------------------------------------------------
 ^
../deps/libffi/src/raw_api.c:1:0: error: unknown value ‘native’ for -march
 /* -----------------------------------------------------------------------
 ^
../deps/libffi/src/closures.c:1:0: error: unknown value ‘native’ for -march
 /* -----------------------------------------------------------------------
 ^
../deps/libffi/src/types.c:1:0: error: unknown value ‘native’ for -march
 /* -----------------------------------------------------------------------
 ^
deps/libffi/ffi.target.mk:110: recipe for target 'Release/obj.target/ffi/deps/libffi/src/prep_cif.o' failed
make: *** [Release/obj.target/ffi/deps/libffi/src/prep_cif.o] Error 1
make: *** Waiting for unfinished jobs....
deps/libffi/ffi.target.mk:110: recipe for target 'Release/obj.target/ffi/deps/libffi/src/raw_api.o' failed
make: *** [Release/obj.target/ffi/deps/libffi/src/raw_api.o] Error 1
deps/libffi/ffi.target.mk:110: recipe for target 'Release/obj.target/ffi/deps/libffi/src/types.o' failed
make: *** [Release/obj.target/ffi/deps/libffi/src/types.o] Error 1
deps/libffi/ffi.target.mk:110: recipe for target 'Release/obj.target/ffi/deps/libffi/src/java_raw_api.o' failed
make: *** [Release/obj.target/ffi/deps/libffi/src/java_raw_api.o] Error 1
deps/libffi/ffi.target.mk:110: recipe for target 'Release/obj.target/ffi/deps/libffi/src/closures.o' failed
make: *** [Release/obj.target/ffi/deps/libffi/src/closures.o] Error 1
make: Leaving directory '/home/chinachu/chinachu/node_modules/ffi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.105-0-pine64-longsleep
gyp ERR! command "/usr/local/nvm/versions/node/v6.9.5/bin/node" "/usr/local/nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/chinachu/chinachu/node_modules/ffi
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 3.10.105-0-pine64-longsleep
npm ERR! argv "/usr/local/nvm/versions/node/v6.9.5/bin/node" "/usr/local/nvm/versions/node/v6.9.5/bin/npm" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi@2.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ffi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ffi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chinachu/chinachu/npm-debug.log
npm WARN checkPermissions Missing write access to /home/chinachu/chinachu/node_modules/superagent
npm WARN checkPermissions Missing write access to /home/chinachu/chinachu/node_modules/swagger-client
chinachu@0.9.5-gamma.0 /home/chinachu/chinachu
├── diskusage@0.1.5 
├── sinon@2.1.0 
└── swagger-client@2.1.13  (git://github.com/kanreisa/swagger-js.git#82abd4fe41dbee957bff51463fcd6167852b3494)

npm ERR! Linux 3.10.105-0-pine64-longsleep
npm ERR! argv "/usr/local/nvm/versions/node/v6.9.5/bin/node" "/usr/local/nvm/versions/node/v6.9.5/bin/npm" "update"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path /home/chinachu/chinachu/node_modules/superagent
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/home/chinachu/chinachu/node_modules/superagent'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/home/chinachu/chinachu/node_modules/superagent'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/chinachu/chinachu/node_modules/superagent' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chinachu/chinachu/npm-debug.log
done.
removed `/home/chinachu/chinachu/usr/src/ffmpeg'
--2017-03-21 14:03:33--  http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz
Resolving johnvansickle.com (johnvansickle.com)... 162.222.226.121
Connecting to johnvansickle.com (johnvansickle.com)|162.222.226.121|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz [following]
--2017-03-21 14:03:33--  https://www.johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz
Resolving www.johnvansickle.com (www.johnvansickle.com)... 162.222.226.121
Connecting to www.johnvansickle.com (www.johnvansickle.com)|162.222.226.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15930956 (15M) [application/x-tar]
Saving to: ‘ffmpeg-release-32bit-static.tar.xz’

ffmpeg-release-32bit-static.ta 100%[====================================================>]  15.19M  4.04MB/s   in 7.1s   

2017-03-21 14:03:41 (2.14 MB/s) - ‘ffmpeg-release-32bit-static.tar.xz’ saved [15930956/15930956]

ffmpeg-release-32bit-static.tar.xz (1/1)
  100 %        15.2 MiB / 130.6 MiB = 0.116    14 MiB/s       0:09             
ffmpeg-3.2.4-32bit-static/ffserver
ffmpeg-3.2.4-32bit-static/GPLv3.txt
ffmpeg-3.2.4-32bit-static/ffmpeg-10bit
ffmpeg-3.2.4-32bit-static/manpages/
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-all.txt
tar: manpages/ffmpeg-all.txt: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffserver.txt
tar: manpages/ffserver.txt: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-bitstream-filters.pdf
tar: manpages/ffmpeg-bitstream-filters.pdf: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-scaler.txt
tar: manpages/ffmpeg-scaler.txt: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-resampler.txt
tar: manpages/ffmpeg-resampler.txt: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-devices.pdf
tar: manpages/ffmpeg-devices.pdf: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-filters.txt
tar: manpages/ffmpeg-filters.txt: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-protocols.pdf
tar: manpages/ffmpeg-protocols.pdf: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-scaler.pdf
tar: manpages/ffmpeg-scaler.pdf: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffprobe.txt
tar: manpages/ffprobe.txt: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-devices.txt
tar: manpages/ffmpeg-devices.txt: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg.pdf
tar: manpages/ffmpeg.pdf: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-formats.pdf
tar: manpages/ffmpeg-formats.pdf: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-codecs.pdf
tar: manpages/ffmpeg-codecs.pdf: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-utils.txt
tar: manpages/ffmpeg-utils.txt: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-resampler.pdf
tar: manpages/ffmpeg-resampler.pdf: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffprobe.pdf
tar: manpages/ffprobe.pdf: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-utils.pdf
tar: manpages/ffmpeg-utils.pdf: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-protocols.txt
tar: manpages/ffmpeg-protocols.txt: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-codecs.txt
tar: manpages/ffmpeg-codecs.txt: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffserver.pdf
tar: manpages/ffserver.pdf: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-filters.pdf
tar: manpages/ffmpeg-filters.pdf: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-bitstream-filters.txt
tar: manpages/ffmpeg-bitstream-filters.txt: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-all.pdf
tar: manpages/ffmpeg-all.pdf: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg.txt
tar: manpages/ffmpeg.txt: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-formats.txt
tar: manpages/ffmpeg-formats.txt: Cannot open: File exists
ffmpeg-3.2.4-32bit-static/ffprobe
tar: manpages: Cannot utime: Operation not permitted
ffmpeg-3.2.4-32bit-static/qt-faststart
ffmpeg-3.2.4-32bit-static/readme.txt
ffmpeg-3.2.4-32bit-static/ffmpeg
tar: Exiting with failure status due to previous errors
removed ‘ffmpeg-release-32bit-static.tar’
Creating libav aliases...
removed ‘/home/chinachu/chinachu/usr/bin/avconv’
removed ‘/home/chinachu/chinachu/usr/bin/avprobe’
‘/home/chinachu/chinachu/usr/bin/avconv’ -> ‘/home/chinachu/chinachu/usr/bin/ffmpeg’
‘/home/chinachu/chinachu/usr/bin/avprobe’ -> ‘/home/chinachu/chinachu/usr/bin/ffprobe’
ffmpeg --> done.
　
　
`npm-install-missing`を叩くとこうなります↓
　
Package         Current  Wanted  Latest  Location
diskusage       MISSING   0.1.5   0.2.1  chinachu
dateformat       1.0.12  1.0.12   2.0.0  chinachu
easy-table        0.2.0   0.2.0   1.0.0  chinachu
http-auth        2.4.11  2.4.11   3.1.3  chinachu
mkdirp            0.3.5   0.3.5   0.5.1  chinachu
mtwitter          1.5.3   1.5.3   1.6.4  chinachu
nodemailer        2.7.2   2.7.2   3.1.7  chinachu
sinon             2.0.0   2.1.0   2.1.0  chinachu
string            1.5.1   1.5.1   3.3.3  chinachu
swagger-client   2.1.13     git     git  chinachu
xml2js            0.2.8   0.2.8  0.4.17  chinachu
[ [ 'diskusage', '0.1.5' ] ]

> ffi@2.2.0 install /home/chinachu/chinachu/node_modules/ffi
> node-gyp rebuild

make: Entering directory '/home/chinachu/chinachu/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
In file included from ../deps/libffi/src/prep_cif.c:27:0:
../deps/libffi/include/ffi_common.h:17:23: fatal error: fficonfig.h: No such file or directory
 #include <fficonfig.h>
                       ^
compilation terminated.
deps/libffi/ffi.target.mk:110: recipe for target 'Release/obj.target/ffi/deps/libffi/src/prep_cif.o' failed
make: *** [Release/obj.target/ffi/deps/libffi/src/prep_cif.o] Error 1
make: Leaving directory '/home/chinachu/chinachu/node_modules/ffi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm-install-missing/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.105-0-pine64-longsleep
gyp ERR! command "/usr/local/nvm/versions/node/v6.9.5/bin/node" "/usr/local/lib/node_modules/npm-install-missing/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/chinachu/chinachu/node_modules/ffi
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm-install-missing: Successfully installed: diskusage@0.1.5tall: Failed to exec install script

ちなみに、
`./chinachu service operator execute`
すると、以下の通りです。

uncaughtException: Error: Cannot find module 'diskusage'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/chinachu/chinachu/app-operator.js:43:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**γはARMだと厳しいでしょうか？**

**Comment by vorbiser** [comment]
nodejsやnpm、Mirakurunがすでに動く状態で、

①./chinachu installer
　で 2) submodule のみをインストールします。

②./chinachu service wui execute
　を実行し、エラーを出させます。

③sudo npm install -g npm-install-missing
　sudo npm-install-missing
　で足りないモジュールを入れます。
②・③を繰り返し行うと無理矢理ですが動くようにはなりました。

**Comment by jrtakahiro** [comment]
ありがとうございます。
何度か②〜③を試しましたが、、変わりそうにありません。


①**`./chinachu installer`**
Chinachu Installer Menu:
[!] These are installed under all /home/chinachu/chinachu/...
[!] Recommend the Auto installation.
1) Auto (full)		3) Node.js Environment	5) ffmpeg
2) submodule		4) Node.js Modules
what do you install? > 2
selected: submodule



②**`./chinachu service wui execute`**
Client {
  basePath: '/api',
  priority: 0,
  host: '',
  port: 40772,
  socketPath: '/var/run/mirakurun.sock',
  userAgent: 'Chinachu/0.9.5-gamma.0 (wui)',
  _userAgent: 'MirakurunClient/2.2.0 Node/v6.9.2 (linux)' }
(node:29821) DeprecationWarning: sys is deprecated. Use util instead.
12 Apr 00:42:29 - HTTP Open Server Listening on { address: '127.0.1.1', family: 'IPv4', port: 20772 }
12 Apr 00:42:29 - HTTP Open Server mDNS advertising started.
12 Apr 00:42:29 - READ: `/home/chinachu/chinachu/rules.json` is updated.
12 Apr 00:42:29 - READ: `/home/chinachu/chinachu/data/schedule.json` is updated.
12 Apr 00:42:29 - READ: `/home/chinachu/chinachu/data/reserves.json` is updated.
12 Apr 00:42:29 - READ: `/home/chinachu/chinachu/data/recording.json` is updated.
12 Apr 00:42:29 - READ: `/home/chinachu/chinachu/data/recorded.json` is updated.


wuiはエラーを吐いていないように見えますが
operatorがエラーです。。
**`./chinachu service operator execute`**
uncaughtException: Error: Cannot find module 'diskusage'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/chinachu/chinachu/app-operator.js:45:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)



③**`sudo npm install -g npm-install-missing`**
/usr/bin/npm-install-missing -> /usr/lib/node_modules/npm-install-missing/bin/npm-install-missing
/usr/lib
`-- npm-install-missing@0.1.4 



③**`sudo npm-install-missing`**
Package         Current  Wanted  Latest  Location
diskusage       MISSING   0.1.5   0.2.1  chinachu
dateformat       1.0.12  1.0.12   2.0.0  chinachu
easy-table        0.2.0   0.2.0   1.1.0  chinachu
http-auth        2.4.11  2.4.11   3.1.3  chinachu
mkdirp            0.3.5   0.3.5   0.5.1  chinachu
mtwitter          1.5.3   1.5.3   1.6.4  chinachu
nodemailer        2.7.2   2.7.2   4.0.0  chinachu
string            1.5.1   1.5.1   3.3.3  chinachu
swagger-client   2.1.13     git     git  chinachu
xml2js            0.2.8   0.2.8  0.4.17  chinachu
[ [ 'diskusage', '0.1.5' ] ]

> ffi@2.2.0 install /home/chinachu/chinachu/node_modules/ffi
> node-gyp rebuild

make: Entering directory '/home/chinachu/chinachu/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
In file included from ../deps/libffi/src/prep_cif.c:27:0:
../deps/libffi/include/ffi_common.h:17:23: fatal error: fficonfig.h: No such file or directory
compilation terminated.
deps/libffi/ffi.target.mk:110: recipe for target 'Release/obj.target/ffi/deps/libffi/src/prep_cif.o' failed
make: *** [Release/obj.target/ffi/deps/libffi/src/prep_cif.o] Error 1
make: Leaving directory '/home/chinachu/chinachu/node_modules/ffi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm-install-missing/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.105-0-pine64-longsleep
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm-install-missing/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/chinachu/chinachu/node_modules/ffi
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm-install-missing: Successfully installed: diskusage@0.1.5tall: Failed to exec install script


npm-install-missingはいつも　fatal error: fficonfig.h: No such file or directory　で失敗しています。

**Comment by vorbiser** [comment]
出来ませんでしたか…orz

https://www.jifu-labo.net/2016/05/mirakurun/2/
Mirakurunの導入はこちらのサイトを参考にnodejs等をインストールしています。
また、chinachuインストールはgit cloneした直後の状態で実行しています。
(当方の環境は Raspberry Pi3 + Raspbian jessie lite + S270(USBドングル)です)

arib-b25-stream-testが動かなかったり(recdvb側で対応)、一部不十分な点があります(

**Comment by Tatsuya-8888** [comment]
私もLinux系は初心者で詳しいことはわからないのですが、
Rasp-Pi3-jessie-pixelとrecdvb(PX-S1UD)で動作出来るようになりました。

私がはまったポイントは先のnode-gyp rebuildの付近で
対応したポイントは、
1. gcc のアップデート 
2. ユーザーchinachuのsudoユーザー登録
3. 上記のnpm-install-missingです。

まっさらなNOOBS OSにインストールしました
他に情報が必要でしたら返信願います。

**Comment by kanreisa** [comment]
Issueを書き込む際はお手数ですが環境情報も書き込んでください。
ARM環境につきましては現状対応予定はありません。
(Mirakurunは対応しています)

**Comment by jrtakahiro** [comment]
失礼しました。
環境は以下の通りです。
・Pine64 2GB
・debian jessie
ARM環境は対応予定なしですね。わかりました。

**Comment by jrtakahiro** [comment]
返信いただきながら遅くなってしまいすみませんでした。

https://www.jifu-labo.net/2016/05/mirakurun/2/
は私も参考にさせていただきましたが、ダメでした。

gcc は最新です。RaspberryPiではないので、まったく同じ環境とはなりません。

betaでは稼働出来たので、γでも稼働できることを期待していましたが、
すみませんがこれでクローズさせていただきます。
ありがとうございました。
