### ISSUE TITLE
./chinachu service wui executeのコマンドを実行するとnode: command not foundとエラーが出てしまいます…

### ISSUE THREAD

**Issue by kimityan555** [Chinachu/Chinachu#319]
Raspberry pi 3上のOSMCにChinachuをインストールしたのですが、./chinachu: line 429: node: command not foundとエラーが出て実行できません。
インストールも結構エラーが出ているようで、でも原因がわかりません。

[http://ksmksks.hateblo.jp/entry/2015/09/20/211813](url)を見ながらインストールしていて、インストール中のエラーの有無はともかく、問題のコマンド実行までは問題なく進んでいます。

what do you install? > 1
selected: Auto (full)
Cloning into 'web/lib/ace'...
fatal: unable to connect to github.com:
github.com[0: 192.30.255.113]: errno=Connection timed out
github.com[1: 192.30.255.112]: errno=Connection timed out

Clone of 'git://github.com/ajaxorg/ace-builds.git' into submodule path 'web/lib/ace' failed
removed `/home/chinachu/chinachu/.nave'
Installing Node using Nave...
converted 'https://github.com/isaacs/nave/archive/v0.5.1.tar.gz' (ANSI_X3.4-1968) -> 'https://github.com/isaacs/nave/archive/v0.5.1.tar.gz' (UTF-8)
--2017-03-28 19:29:53--  https://github.com/isaacs/nave/archive/v0.5.1.tar.gz
Resolving github.com (github.com)... 192.30.255.112, 192.30.255.113
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/isaacs/nave/tar.gz/v0.5.1 [following]
converted 'https://codeload.github.com/isaacs/nave/tar.gz/v0.5.1' (ANSI_X3.4-1968) -> 'https://codeload.github.com/isaacs/nave/tar.gz/v0.5.1' (UTF-8)
--2017-03-28 19:29:54--  https://codeload.github.com/isaacs/nave/tar.gz/v0.5.1
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7640 (7.5K) [application/x-gzip]
Saving to: 'STDOUT'

-                             100%[================================================>]   7.46K  --.-KB/s   in 0.002s

2017-03-28 19:30:00 (3.34 MB/s) - written to stdout [7640/7640]

nave-0.5.1/nave.sh
removed directory: '/home/chinachu/chinachu/.nave/nave-0.5.1'

curl: (22) The requested URL returned error: 404 Not Found
######################################################################## 100.0%
curl: (22) The requested URL returned error: 404 Not Found
Binary download failed, trying source.

curl: (22) The requested URL returned error: 404 Not Found
######################################################################## 100.0%
fetched from http://nodejs.org/dist/v6.9.2/node-v6.9.2.tar.gz
/home/chinachu/chinachu/.nave/nave.sh: line 292: sysctl: command not found
creating  ./icu_config.gypi
* Using ICU in deps/icu-small
creating  ./icu_config.gypi
{ 'target_defaults': { 'cflags': [],
                       'default_configuration': 'Release',
                       'defines': [],
                       'include_dirs': [],
                       'libraries': []},
  'variables': { 'arm_float_abi': 'hard',
                 'arm_fpu': 'vfpv3',
                 'arm_thumb': 0,
                 'arm_version': '7',
                 'asan': 0,
                 'debug_devtools': 'node',
                 'force_dynamic_crt': 0,
                 'gas_version': '2.25',
                 'host_arch': 'arm',
                 'icu_data_file': 'icudt57l.dat',
                 'icu_data_in': '../../deps/icu-small/source/data/in/icudt57l.dat',
                 'icu_endianness': 'l',
                 'icu_gyp_path': 'tools/icu/icu-generic.gyp',
                 'icu_locales': 'en,root',
                 'icu_path': 'deps/icu-small',
                 'icu_small': 'true',
                 'icu_ver_major': '57',
                 'node_byteorder': 'little',
                 'node_enable_d8': 'false',
                 'node_enable_v8_vtunejit': 'false',
                 'node_install_npm': 'true',
                 'node_module_version': 48,
                 'node_no_browser_globals': 'false',
                 'node_prefix': '/home/chinachu/chinachu/.nave/installed/6.9.2',
                 'node_release_urlbase': '',
                 'node_shared': 'false',
                 'node_shared_cares': 'false',
                 'node_shared_http_parser': 'false',
                 'node_shared_libuv': 'false',
                 'node_shared_openssl': 'false',
                 'node_shared_zlib': 'false',
                 'node_tag': '',
                 'node_use_bundled_v8': 'true',
                 'node_use_dtrace': 'false',
                 'node_use_etw': 'false',
                 'node_use_lttng': 'false',
                 'node_use_openssl': 'true',
                 'node_use_perfctr': 'false',
                 'node_use_v8_platform': 'true',
                 'openssl_fips': '',
                 'openssl_no_asm': 0,
                 'shlib_suffix': 'so.48',
                 'target_arch': 'arm',
                 'uv_parent_path': '/deps/uv/',
                 'uv_use_dtrace': 'false',
                 'v8_enable_gdbjit': 0,
                 'v8_enable_i18n_support': 1,
                 'v8_inspector': 'true',
                 'v8_no_strict_aliasing': 1,
                 'v8_optimized_debug': 0,
                 'v8_random_seed': 0,
                 'v8_use_snapshot': 'true',
                 'want_separate_host_toolset': 0}}
creating  ./config.gypi
creating  ./config.mk
make -C out BUILDTYPE=Release V=1
make[1]: Entering directory '/home/chinachu/chinachu/.nave/src/6.9.2/out'
  g++  -I../deps/gtest -I../deps/gtest/include  -pthread -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /home/chinachu/chinachu/.nave/src/6.9.2/out/Release/.deps//home/chinachu/chinachu/.nave/src/6.9.2/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o.d.raw  -O2 -w -pipe -march=native -c -o /home/chinachu/chinachu/.nave/src/6.9.2/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o ../deps/gtest/src/gtest-death-test.cc
  g++  -I../deps/gtest -I../deps/gtest/include  -pthread -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /home/chinachu/chinachu/.nave/src/6.9.2/out/Release/.deps//home/chinachu/chinachu/.nave/src/6.9.2/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o.d.raw  -O2 -w -pipe -march=native -c -o /home/chinachu/chinachu/.nave/src/6.9.2/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o ../deps/gtest/src/gtest-filepath.cc
*** Error in `g++': double free or corruption (top): 0x005ccf08 ***
deps/gtest/gtest.target.mk:79: recipe for target '/home/chinachu/chinachu/.nave/src/6.9.2/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o' failed
make[1]: *** [/home/chinachu/chinachu/.nave/src/6.9.2/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o] Aborted
make[1]: *** Waiting for unfinished jobs....
*** Error in `g++': double free or corruption (top): 0x010e7ef8 ***
deps/gtest/gtest.target.mk:79: recipe for target '/home/chinachu/chinachu/.nave/src/6.9.2/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o' failed
make[1]: *** [/home/chinachu/chinachu/.nave/src/6.9.2/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o] Aborted
make[1]: Leaving directory '/home/chinachu/chinachu/.nave/src/6.9.2/out'
Makefile:68: recipe for target 'node' failed
make: *** [node] Error 2
Failed to make 6.9.2
fail
'/home/chinachu/chinachu/.nave/node' -> '/home/chinachu/chinachu/.nave/installed/6.9.2/bin/node'
'/home/chinachu/chinachu/.nave/npm' -> '/home/chinachu/chinachu/.nave/installed/6.9.2/bin/npm'
done.
Installing Node Modules using NPM...
./chinachu: line 157: npm: command not found
./chinachu: line 158: npm: command not found
done.
removed `/home/chinachu/chinachu/usr/src/ffmpeg'
converted 'http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz' (ANSI_X3.4-1968) -> 'http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz' (UTF-8)
--2017-03-28 19:31:48--  http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz
Resolving johnvansickle.com (johnvansickle.com)... 162.222.226.121
Connecting to johnvansickle.com (johnvansickle.com)|162.222.226.121|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz [following]
converted 'https://www.johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz' (ANSI_X3.4-1968) -> 'https://www.johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz' (UTF-8)
--2017-03-28 19:31:49--  https://www.johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz
Resolving www.johnvansickle.com (www.johnvansickle.com)... 162.222.226.121
Connecting to www.johnvansickle.com (www.johnvansickle.com)|162.222.226.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15930956 (15M) [application/x-tar]
Saving to: 'ffmpeg-release-32bit-static.tar.xz'

ffmpeg-release-32bit-static.t 100%[================================================>]  15.19M   368KB/s   in 36s

2017-03-28 19:32:25 (434 KB/s) - 'ffmpeg-release-32bit-static.tar.xz' saved [15930956/15930956]

ffmpeg-release-32bit-static.tar.xz (1/1)
  100 %        15.2 MiB / 130.6 MiB = 0.116   9.0 MiB/s       0:14
ffmpeg-3.2.4-32bit-static/ffserver
ffmpeg-3.2.4-32bit-static/GPLv3.txt
ffmpeg-3.2.4-32bit-static/ffmpeg-10bit
ffmpeg-3.2.4-32bit-static/manpages/
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-all.txt
ffmpeg-3.2.4-32bit-static/manpages/ffserver.txt
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-bitstream-filters.pdf
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-scaler.txt
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-resampler.txt
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-devices.pdf
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-filters.txt
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-protocols.pdf
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-scaler.pdf
ffmpeg-3.2.4-32bit-static/manpages/ffprobe.txt
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-devices.txt
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg.pdf
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-formats.pdf
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-codecs.pdf
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-utils.txt
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-resampler.pdf
ffmpeg-3.2.4-32bit-static/manpages/ffprobe.pdf
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-utils.pdf
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-protocols.txt
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-codecs.txt
ffmpeg-3.2.4-32bit-static/manpages/ffserver.pdf
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-filters.pdf
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-bitstream-filters.txt
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-all.pdf
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg.txt
ffmpeg-3.2.4-32bit-static/manpages/ffmpeg-formats.txt
ffmpeg-3.2.4-32bit-static/ffprobe
ffmpeg-3.2.4-32bit-static/qt-faststart
ffmpeg-3.2.4-32bit-static/readme.txt
ffmpeg-3.2.4-32bit-static/ffmpeg
removed 'ffmpeg-release-32bit-static.tar'
Creating libav aliases...
removed '/home/chinachu/chinachu/usr/bin/avconv'
removed '/home/chinachu/chinachu/usr/bin/avprobe'
'/home/chinachu/chinachu/usr/bin/avconv' -> '/home/chinachu/chinachu/usr/bin/ffmpeg'
'/home/chinachu/chinachu/usr/bin/avprobe' -> '/home/chinachu/chinachu/usr/bin/ffprobe'
ffmpeg --> done.
chinachu@osmc:~/chinachu$ ./chinachu service wui execute
./chinachu: line 429: node: command not found
failed somehow

インストールのログはこんな感じです。
404エラーとかが結構あるので、何かのダウンロードに失敗しているのでしょうか？
最初のCloning into 'web/lib/ace'...の部分がとにかく長いです。3分くらい

nodeというコマンドは実行できないので、インストールができていないのでしょうが、インストールの仕方もよくわからないです。

**Comment by kanreisa** [comment]
amd64 / x86 以外の環境はサポートしていないため、
自前で Node と ffmpeg のインストールを行う必要があります。

**Comment by kimityan555** [comment]
ありがとうございます。
いろいろとRaspberry pi用の方法でインストールしていって、インストーラーの動作が今までより明らかに変わりました。
./chinachu service wui executeで、WUIへのアクセスも無事できました。
（OSMCのGUIで使うので、今後そんなに見ることもない…）

しかし、番組表が空なので、所得しようとsudo ./chinachu updateを実行したところ、
Client {
  basePath: '/api',
  priority: 0,
  host: '',
  port: 40772,
  socketPath: '/var/run/mirakurun.sock',
  userAgent: 'Chinachu/0.9.5-gamma.0 (scheduler)',
  _userAgent: 'MirakurunClient/2.2.0 Node/v7.8.0 (linux)' }
31 Mar 14:53:17 - GETTING EPG from Mirakurun.
(node:1354) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [object Object]
(node:1354) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
とエラーが出てしまいました。

インストーラーを実行したところ、
2と3では特に目立ったエラーは出ていませんでした。
（見逃しただけかもしれません）
しかし4のところでエラーが出てきました。
nodeのモジュールというのも別でインストールしたので、おそらくここのエラーは無視してもいいと考えています。
5でもおそらく何のエラーもなくインストールができていると思います。

エラーを見る限りではnode.jsのプロセスが止まったみたいな解釈ですが、エラーを調べてみても解決方法がさっぱりです。
何が原因か、わかりますでしょうか？

あと一つ気になったのが、GETTING EPG from Mirakurunのところなのですが、チューナーは直接USBで取り付けたので、ネット経由である必要はないと思うのですが、こういう仕様ですか？
それとも設定が間違っていますか？

**Comment by takaakis62** [comment]
参考にしている情報がChinachu βのもののようですね。
最新版のChinachu γではMirakurunの導入が必須になっています。
こちらの情報を参考に移行してみてください。
https://github.com/Chinachu/Chinachu/wiki/Migration-Guide-of-Beta-to-Gamma

**Comment by kimityan555** [comment]
ありがとうございます。
調べてみたら、つい最近γに変わったんですね。
知りませんでした。

確かにインストールされているものもγみたいです。
そこで、MirakurunのインストールからChinchuのインストールまでやり直してみました。
しかし、やっぱりエラーが出ました。
sudo ./chinachu updateを実行すると、
module.js:591
    throw err;
    ^

SyntaxError: /home/chinachu/chinachu/config.json: Unexpected string in JSON at position 701
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:588:27)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/chinachu/chinachu/app-scheduler.js:48:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
failed somehow
といったエラーが出てきます。
どうやらconfig.jsonの設定に失敗したようですが、設定の項目に何があるのかわからないうえ、情けないことにβに合わせてほとんど消してしまったので、何を書いておかないといけないのかがわかりません…。

今のところこんな感じです。
{
  "recordedDir" : "/rec/",
  "tenporaryDir": "/tmp/",


  "wuiUsers": [
  ],
  "wuiAllowCountries": ["JP"],

  "wuiPort"                  : "10772",
  "wuiHost"                  : "::",
  "wuiTlsKeyPath"            : null,
  "wuiTlsCertPath"           : null,
  "wuiOpenServer"            : false,
  "wuiOpenPort"              : 20772,
  "wuiXFF"                   : false,
  "wuiPreviewer"             : true,
  "wuiStreamer"              : true,
  "wuiFiler"                 : true,
  "wuiConfigurator"          : true,

  "recordedFormat"           : "<category>/<title>[<channel><channel-name>]<full

 "mirakurunPath": "/var/run/mirakurun.sock"

  "storageLowSpaceThresholdMB": 100,
  "storageLowSpaceAction": "none",

}
録画にはOSMC(kodi)のPVR TVのアドオンで、Chinachuに[(https://github.com/mzyy94/Chinachu-IPTV-API-addon)]のアドオンを追加してGUIから実行する予定なので、WUIの必要性がデバッグ時以外なくログインなどの部分は空白にしています。
ログインはできます。

Mirakurunの設定は済ませてあります。
チューナーがKTV-FSUSB2なので、
name: FSUSB2
  types: GR
  command:sudo recfsusb2n --d25 --strip <channel> - -
  isDisabled: false
で、あっていると思います。

チャンネルは
- name: Toukai TV
  type: GR
  channel: '21'

- name: NHK E
  type: GR
  channel: '13'

- name: NHK G
  type: GR
  channel: '20'

- name: Chukyo TV
  type: GR
  channel: '19'

- name: CBC
  type: GR
  channel: '18'

- name: Nagoya TV
  type: GR
  channel: '22'

- name: Mie TV
  type: GR
  channel: '27'

- name: TV Aichi
  type: GR
  channel: '27
日本語で打っていたところ文字化けしだしたのでローマ字で妥協。

このほかは変えてないです。

何がいけないんでしょうか？

**Comment by kanreisa** [comment]
"recordedFormat" : "/<title>[]<full
ここと
"storageLowSpaceAction": "none",
ここがおかしいですね。

}の前に,(カンマ)を入れてはいけません。

**Comment by kimityan555** [comment]
ありがとうございます。
家族で旅行に行っていたもので、返信遅れて申し訳ありません。

ご指摘いただいた箇所を修正してみましたが、別のエラーが出ました。
前のエラーは修正する前でもでなく、何かの偶然で出ていたようです。

node.jsのバージョンが7.8.0だったので6.10.1に落としてみましたがエラーは変わらずでした。
そこで、rivarunを入れてrivarun --list | sed 's/},/},\n/g'を実行してみると、どうやら/var/run/mirakurun.sockのファイルが生成されていないようで…

結局チャンネルの設定を書き直したらうまく動いたので、もしかしたら全角を打とうとしたときの名残だったのかもしれません。
rivarun --list | sed 's/},/},\n/g'を実行したところ、無事にEPG所得に成功しました。

しかし、sudo ./chinachu updateではやっぱりエラーが出てしまいました。
Client {
  basePath: '/var/run/mirakurun.sock/api',
  priority: 0,
  host: null,
  port: null,
  socketPath: '/var/run/mirakurun.sock',
  userAgent: 'Chinachu/0.9.5-gamma.0 (scheduler)',
  _userAgent: 'MirakurunClient/2.2.0 Node/v6.10.1 (linux)' }
2 Apr 21:38:40 - GETTING EPG from Mirakurun.
(node:3211) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [object Object]

ハンドルされていないエラーがなんちゃらかんちゃらと、解決方法がわかりません。
mirakurunのログではエラーは出ておらず、chinachuのログでも原因がわかるようなエラーは見当たりませんでした。

ログで、basePathに/var/run/mirakurun.sock/apiと出るのはmirakurun.sockの中のデータの参照という意味でしょうか？
それとも何かの設定ミスですか？

**Comment by kimityan555** [comment]
ありがとうございました。
いろいろといろいろして、何とか映るようにはなりました。
録画や、再生、ストリーミングによるライブ視聴、さらにはRaspberry Piにはきついですが、本体での視聴もできています。

また何かあったらよろしくお願いします。
