### ISSUE TITLE
アップデート後からエラーorz

### ISSUE THREAD

**Issue by nomiu26** [Chinachu/Chinachu#325]
# ./chinachu service operator execute
[fatal] 'uid' required in config.
failed somehow

おかしなところ無いんだけどな・・・
https://github.com/Chinachu/Chinachu/wiki/Gamma-Configuration
もしかしてここの情報古い？

**Comment by taikoyaP** [comment]
当該ページには、uidは必須と書いてあると思うのですが。

**Comment by taikoyaP** [comment]
あ、すみません。pm2ではなくsystemdの場合ですね。失礼しました。
(個人的にはpm2に移行してしまったのでsystemdの場合は分からないです)

**Comment by rkarsnk** [comment]
app-operator.jsの71行目以降を見る限り。config.jsonにuidがないと停止するようになっているみたいです。

``` javascript
// setuid 
if (process.platform !== "win32") {
	if (process.getuid() === 0) {
		if (typeof config.gid === "string" || typeof config.gid === "number") {
			process.setgid(config.gid);
		} else {
			process.setgid('video');
		}
		if (typeof config.uid === "string" || typeof config.uid === "number") {
			process.setuid(config.uid);
		} else {
			console.error("[fatal] 'uid' required in config.");
			process.exit(1);
		}
	}
}
```

**Comment by nomiu26** [comment]
すいません。uid変更したら問題なく動作しました。
