### ISSUE TITLE
録画ファイルチェックエラー (キャッシュ削除で解決？)

### ISSUE THREAD

**Issue by inyuito** [Chinachu/Chinachu#326]
録画済リストで一部のファイルが「この番組の録画ファイルは移動または削除されています」と表示されます。
なおファイルは存在しておりWebUIの削除ボタンで消えます。ただ上記エラーのためダウンロードおよびストリーミング再生は不可。

エラーが出るため設定にて
"recordedFormat": "[<date:yymmdd-HHMM>][<type><channel-sid>].m2ts",
と指定しましたがそれでもエラーになります。
ただならないものもあるのでrecorded.jsonが関係しているのかなと思ったりしています。

https://cope.jp/recorded.json
/mnt/hdd2/samba/TV-Rec/[170508-0115][BS192].m2tsがエラー対象です

ほかの方はそういった症状は出てないのかな。。。
何か解決策があればよろしくお願いします。

**Comment by falconws** [comment]
commit f1a825439f29341da805cbe7a1f01fd81777fad1
の Chinachu で、自分も同じ症状が発生しています。
全てのファイルではなく一部のファイルで、どういう条件で発生するのかよくわかりません・・。。

**Comment by kanreisa** [comment]
環境情報を詳しく書いてください。
大抵の場合は権限がおかしくなっています。

**Comment by inyuito** [comment]
Ubuntu 16.04.2 LTS(Linux Tiger 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)
Mem: 16GB
CPU:  i3-3220
SubHDD: 6TB-RAID
録画データ保存媒体は外付けRAID-HDD(HDDケースの特殊な仕様によりパーミッションの変更不可)
上記症状のファイルと正常ファイルの所有者・権限共に同じです。(変更できないので違う事はあり得ないです。)

権限とはファイルのパーミッションの事を指しているのでしょうか？
あとWebUIにて削除は出来るのが不思議です。
またChinachu Betaでは正常に動作しておりました。

ちなみにファイルのチェックは存在するかどうかだけチェックしているのでしょうか？
それだと削除で指定するパスとファイルチェックで指定するパスが違うのかな
なんて思ってみたり

**Comment by kanreisa** [comment]
* Chinachu は PM2 で動作していますか？以前の方法で動作していますか？
* 正常なファイルとそうでないファイルのパーミッションは本当に同一ですか？GIDも含めて
* ストレージはどのようにマウントしていますか？fstab等ではどのように指定していますか？

**Comment by inyuito** [comment]
PM2で動作しているか確認する方法はありますか？
ps aux|grep  chinachu 
chinachu 15903  0.0  0.0  12584  2244 ?        S    00:23   0:00 /bin/bash /home/chinachu/chinachu/chinachu service wui execute
chinachu 15909  0.4  0.8 1317812 138848 ?      Sl   00:23   6:31 node app-wui.js
chinachu 15910  0.0  0.0   7028   580 ?        S    00:23   0:00 tee -a ./log/wui
chinachu 28543  0.0  0.0  12584  2356 ?        S    03:21   0:00 /bin/bash /home/chinachu/chinachu/chinachu service operator execute

ls -labhn /mnt/hdd2/samba/TV-Rec/
https://cope.jp/chinachu/ls

cat fstab
https://cope.jp/chinachu/fstab

**Comment by kanreisa** [comment]
PM2ではないようですね。
当該APIが叩かれた時ログには何か出ていませんか？

**Comment by inyuito** [comment]
PM2に変更した方がいいですか？

https://cope.jp/chinachu/log/
8 May 03:34:16 - FIN: #iduewq1 2017-05-08T01:15:00+0900 [ＷＯＷＯＷライブ] ジャンゴ　繋がれざる者（吹替版）[R15+指定]

くらいですかね？

**Comment by inyuito** [comment]
あ、、症状がわかりました。

**Comment by inyuito** [comment]
あー。。
なんかChromeのキャッシュを削除したら解決しました。。。

**Comment by kanreisa** [comment]
解決したようで安心しました。
また何かあればご報告ください。
