### ISSUE TITLE
自動予約番組のスキップAPI

### ISSUE THREAD

**Issue by sugtao4423** [Chinachu/Chinachu#328]
wikiのAPI一覧を見たところ、ルールから自動予約された番組をスキップさせるAPIがないようなのでissueを書かせていただきました。

実装のご検討よろしくお願いします。

**Comment by kanreisa** [comment]
WebUI は全部APIを使っているので、既にあるはずです👍

**Comment by sugtao4423** [comment]
すみません、WebUIのソースコード見たらありましたね・・・

`/:id/skip.json`
`/:id/unskip.json`
にputで良かったのですね

お騒がせしました。ありがとうございました。
クローズさせていただきます。
