### ISSUE TITLE
pm2から起動した場合に、WUIから見えるシステムステータスが「停止しています」になってしまう

### ISSUE THREAD

**Issue by sawaken** [Chinachu/Chinachu#330]
```
sudo pm2 start processes.json
```
によってoperatorとwuiを起動した場合、PIDファイルがそれぞれ
`/usr/local/var/run/chinachu-operator.pid`と`/usr/local/var/run/chinachu-wui.pid`に保存される設定になっているため、https://github.com/Chinachu/Chinachu/blob/gamma/app-wui.js#L951
においてプロセスの捕捉が上手くいかないのではないでしょうか。

**Comment by Corsaire01** [comment]
#332 で同じ現象です。
ちなみに、そちらは登録することはできますか。

**Comment by Corsaire01** [comment]
#332 で修正して見ました。
ご確認ください。

**Comment by epgdatacapbon** [comment]
現在の最新commitでも同様の不具合を確認しています。
https://github.com/Chinachu/Chinachu/commit/9ff5fe56f37245e272ac63082db36f8bafac14d9

**Comment by kanreisa** [comment]
公式で修正しますので、 #332 は適用しないでください。手順を誤ると環境を壊します。

**Comment by kanreisa** [comment]
track upstream bug: https://github.com/Unitech/pm2/issues/3102

**Comment by kanreisa** [comment]
@sawaken @epgdatacapbon
PM2公式でバグ修正のマージ待つ間、下記お試しください。
```
cd ~/chinachu/
sudo npm install -g @kanreisa/pm2
pm2 update
pm2 delete processes.json
pm2 start processes.json
pm2 save
```

**Comment by kanreisa** [comment]
修正しました。
