### ISSUE TITLE
ライブ視聴用のサムネイルを取得したいです

### ISSUE THREAD

**Issue by airwhite** [Chinachu/Chinachu#333]
日々の開発お疲れ様です。
ライブ視聴用のサムネイル画像を提供するapiは追加できないでしょうか。
/api/channel/:programId/preview みたいな感じなのですが・・・
/api/channel/broadcasting.json から各チャンネルのサムネイルを引っ張ろうと考えています。

**Comment by kanreisa** [comment]
パフォーマンス的な問題で、対応できなさそうですが、何か妙案があればご提案ください！
