### ISSUE TITLE
ルール作成時のチャンネルの表記について

### ISSUE THREAD

**Issue by suzuiro** [Chinachu/Chinachu#334]
BSプレミアムを予約する場合、Betaでは"BS_103"と表示されていたのがGammaでは"8kpz"と表示され、分かりにくく感じます。Betaのように表示できないでしょうか。

**Comment by kanreisa** [comment]
こんにちは！
`BS_103`のようなCH指定はGammaでも可能ですが、Gammaではデフォルトで自動指定する際にサービスを対象とするようにしているため、そのようになっています。

`BS_103` ... 物理チャンネル (チューナー引数) 指定
`8kpz` ... サービスID 指定

となります。Airでは気の利いた表示になる予定ですのでどうかよろしくお願いいたします。

**Comment by suzuiro** [comment]
返答ありがとうございます。
サービスIDだったのですね。Airに期待したいと思います。
