### ISSUE TITLE
予約した番組がすぐに録画済みになってしまう

### ISSUE THREAD

**Issue by falscyuto** [Chinachu/Chinachu#336]
番組を予約しても、全く録画されずに録画ファイルを作ってすぐに録画済みになってしまいます。

**Comment by kanreisa** [comment]
こんにちは。

ログは確認しましたか？

**Comment by falscyuto** [comment]
このような感じになってます
`18 Oct 21:24:47 - PREPARE: #381jqz0dva 2017-10-18T21:25:00+0900 [ＮＨＫＥテレ１東京] きょうの料理ビギナーズ
18 Oct 21:24:47 - WRITE: /home/yuto/chinachu/data/recording.json
18 Oct 21:24:47 - RECORD: #381jqz0dva 2017-10-18T21:25:00+0900 [ＮＨＫＥテレ１東京] きょうの料理ビギナーズ
18 Oct 21:24:47 - STREAM: /home/yuto/Documents/recordedi/[171018-2125][GR26][ＮＨＫＥテレ１東京]きょうの料理ビギナーズ.m2ts
18 Oct 21:24:47 - WRITE: /home/yuto/chinachu/data/recording.json
18 Oct 21:24:47 - WRITE: /home/yuto/chinachu/data/recorded.json
18 Oct 21:24:47 - WRITE: /home/yuto/chinachu/data/recording.json
18 Oct 21:24:47 - WRITE: /home/yuto/chinachu/data/reserves.json
18 Oct 21:24:47 - FIN: #381jqz0dva 2017-10-18T21:25:00+0900 [ＮＨＫＥテレ１東京] きょうの料理ビギナーズ
18 Oct 21:24:48 - READ: `/home/yuto/chinachu/data/recorded.json` is updated.
18 Oct 21:24:48 - READ: `/home/yuto/chinachu/data/reserves.json` is updated.
18 Oct 21:34:02 - SPAWN: node app-scheduler.js (pid=5384)
18 Oct 21:34:02 - STREAM: ./log/scheduler
18 Oct 21:34:03 - EXIT: node app-scheduler.js (pid=5384)
18 Oct 21:34:04 - READ: `/home/yuto/chinachu/data/reserves.json` is updated.`

**Comment by kanreisa** [comment]
これだけじゃ全く分からないですね～
Mirakurunのログも見ないと分からないですね

**Comment by falscyuto** [comment]
@kanreisa 調べてみたところ、自分のpcで"rivarun"を使った録画が以下のようなエラーを吐きうまくできてないようなのですが、今のChinachuγでは関係ありますか？
```
$ rivarun --b25 --sid 1024 --ch GR/27 15 test.ts
status: 200
headers: {"server":"Mirakurun/2.5.7","content-type":"video/MP2T","date":"Wed, 18 Oct 2017 15:39:11 GMT","connection":"close","transfer-encoding":"chunked"}
```

**Comment by kanreisa** [comment]
200はエラーじゃないですね

**Comment by falscyuto** [comment]
いまいち原因はわかりませんでしたが、とりあえず必要そうなパッケージをインストールしなおしたら一応動くようにはなりました。
お手数おかけしました。
