### ISSUE TITLE
録画開始までの遊び

### ISSUE THREAD

**Issue by falscyuto** [Chinachu/Chinachu#339]
Chinachuγにアップデートした後、"operRecPrepTime"は使用できますか？

**Comment by kanreisa** [comment]
使用できませんが、Mirakurunの設定 `maxBufferBytesBeforeReady` で微調整することが出来ます（非推奨）。
https://github.com/Chinachu/Mirakurun/blob/master/doc/Configuration.md#structure

**Comment by falscyuto** [comment]
わかりました。ありがとうございます。
