### ISSUE TITLE
スマホレイアウトでのスクロールバグ

### ISSUE THREAD

**Issue by unlimish** [Chinachu/Chinachu#341]
スマホからChinachuの管理ページにアクセスして、予約条件を設定する画面や、番組表の表示条件設定の画面で、スクロールをしようとしてもスクロールが行えない。

**Comment by oga6** [comment]
Mozilla/5.0 (Linux; Android 7.0; MI 5s Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36

**Comment by kanreisa** [comment]
iPhone では再現しませんでしたが、 Android (Chrome) で再現しました。

**Comment by unlimish** [comment]
iOS上で発生しているバグもIssueに追加しておきました。
