### ISSUE TITLE
[Question] LAN 内で認証を追加する方法

### ISSUE THREAD

**Issue by falconws** [Chinachu/Chinachu#343]
Chinachu の Web UI へ認証を追加する方法をご教示ください。
もしドキュメントに記載の内容でしたら、すみません。
config.sample.json をベースに少し変更を加えていますが、Wiki を見る限り関連しそうなのは
<pre>
wuiOpenServer | boolean | (true) | no | LAN用の無認証サーバーを使う
</pre>
この設定かと思いまして、
<pre>
wuiOpenServer": false,
</pre>
として
<pre>
$ sudo pm2 restart chinachu-operator chinachu-wui
</pre>
とした所、ポート 20772 での LISTEN すらなくなり Web UI へアクセスできなくなります。
Chinachu BETA 時代の BASIC 認証を追加したいだけなのですが、どうすれば良いか
ポインタだけでもご教示頂けないでしょうか。

よろしくお願いします。

**Comment by kanreisa** [comment]
`wuiHost` `wuiPort` `wuiUsers` を設定するとβ同等の機能が利用できますが、廃止予定ですので、
`wuiOpenHost` を `127.0.0.1` とでも設定して、 `nginx` や Docker 等で認証プロキシを立てると良いです。

**Comment by falconws** [comment]
ご回答頂きまして、まことにありがとうございます。
教えて頂いた通り設定すると、確かに認証できました。
この機能は良い機能だと思うのですが、廃止する理由ってどういった理由によるものなのでしょうか？

また、少し横道に話がそれてしまうのですが、今回のように config.json を変更した場合の
Chinachu への反映は、
<pre>
$ sudo pm2 restart chinachu-operator chinachu-wui
</pre>
で良いでしょうか？
同様に、mirakurun のチャンネル設定などを変更した場合も
<pre>
$ sudo pm2 restart mirakurun-server
</pre>
で良いでしょうか？

**Comment by kanreisa** [comment]
> 廃止する理由
元々無保証なので自己責任で運用していただくのが当たり前なのですが、認証機能がある以上それを過信してインターネット上に晒したりする例が多く、建前を維持するのが難しくなったためです。また、LAN専用のサーバーである立場を改めて明確にする意図があります。
この廃止予定の機能を使うなとは言えないのですが、開発者としてはお勧めいたしません。認証は自己責任で別途用意して頂くか、VPNを利用してください。
次期バージョンでは完全に廃止する代わりに代替手段を用意しています。

> Chinachu への反映は
はい、それで構いません。今回の場合は `chinachu-wui` のみでも結構です。

> Mirakurun
```
mirakurun restart
```
を推奨しています

**Comment by falconws** [comment]
廃止する理由について
ご教示ありがとうございます。
うちの場合は LAN 内でしか使用しないので、とりあえずこの機能を使わせて頂くようにします。
次期バージョンでの代替手段にも期待しています。
Chinachu は、自前で Web サーバや DB サーバ等構築することなく使えるという点も
ユーザ目線で見ると大変ありがたいので、認証機能の為だけに別途 Nginx 等を
構築するというのはちょっとキツいかなと思ってます。

それぞれの設定の反映について、了解致しました。

**Comment by falconws** [comment]
おかげさまで解決しましたので、本 Issue クローズとさせて頂きます。

**Comment by kanreisa** [comment]
> うちの場合は LAN 内でしか使用しないので、

インターネットに接続していますよね？NAT配下であっても危険な機能です。という認識を、持ってください。

> 認証機能の為だけに別途 Nginx 等を構築するというのはちょっとキツい

Docker を使えば良いのです。 https://qiita.com/kei-sato/items/8b0a7fa645c66bdf6d6c

Chinachu はエンドユーザー向けに完成させてはいないのです。大人の事情もあるのだとご理解ください。

**Comment by falconws** [comment]
> インターネットに接続していますよね？NAT配下であっても危険な機能です。という認識を、持ってください。

インターネットには接続していますが、NAT 設定はしていない（いわゆるポート開放はしていない）のですが、
それでも同じことでしょうか？（前のコメントで言われているブルートフォース等はそもそも認証まで
WAN 側から到達できないので不可能かと思いますが・・・）

Docker 使ったことがないので、時間見つけて勉強してみたいと思います。
参考リンクありがとうございます。

**Comment by kanreisa** [comment]
是非知っておいていただきたいので紹介しますと... https://ngrok.com/
こういった簡単にトンネルを掘る技術なんか使われるとどっかの穴から入って来られます。
なので、こんな単純で何も対策されていない認証を(開発者が言ってるのですから間違いありません)過信して "不可能かと" と思っていると
いつの間にかやられることがあるかもしれません。
本当に今海外からの不正アクセスが増えてるので、ご注意願いたいとおもいます。

どうぞ、よろしくお願いいたします。

**Comment by falconws** [comment]
ngrok の紹介及び注意喚起、ありがとうございます。
こちらは、私が ngrok を使用して誤って外部公開してしまっている場合には
例え NAT 設定されていなくても WAN 側から Chinachu へ到達可能ということだと
思いますが、こういったサービス等も使用していないので、経路的には到達できないものと思います。
仮に私が WAN 側から到達しようと考えるのであれば、ssh で該当サーバへ入って
ssh port forwarding するか、あるいは VPN かの2通りぐらいなので、それ以外で
攻撃者が攻撃するのは、なかなか難しいのではないかと思いますが、
海外から不正アクセスが増えている事も仕事柄承知している為、気を付けたいと思います。

**Comment by kanreisa** [comment]
どうやら伝えようとしてた事が伝わってないようです。
ngrok を例にあげると、それを使っていなくても、です。
文面から見て、かなり過信している様子が伺えます。
また、不用意にこのような場でも経路について書かないでください。

私は立場上、ここで廃止予定の機能について聞かれたら当然それをネガティブに表現しますし、
危険な可能性のあることははっきりとお伝えします。

というわけですので、どうぞよろしくお願いいたします。

**Comment by falconws** [comment]
すみません。意図が掴みきれていないとのことと、内容が不適切であるとのことなので、
一旦１つ前のコメントは削除させて頂きました。

**Comment by simplelife0530** [comment]
横から失礼します。

不正アクセスをするのは、侵入者が悪い人です。
そもそも録画したデータは、無料で公開されているデータだったはずで、不正アクセスで盗られても、本人が困るわけではありません。

サーバを立てた側の責任というより、侵入者が罪に問われるわけです。

もちろん、TV局側は、うれしくはないと思いますが、侵入者が罰せられることはあっても、サーバー所有者がそこまで責任を問われるとは思えないです。

2018年1月5日 20:36 K <notifications@github.com>:
