### ISSUE TITLE
番組表をMirakurunから取得中にエラーが発生したらログを出して欲しい

### ISSUE THREAD

**Issue by KOBA789** [Chinachu/Chinachu#344]
この辺で `.catch()` してログに出すべきだと思われます。

https://github.com/Chinachu/Chinachu/blob/4c2a7f6/app-scheduler.js#L602

Mirakurun のホスト名 typo したままログ見ても原因がわからなくてつらかったので、エラーログあるとよさそうです。

本当は PR にしたかったのですがログの吐き方のお作法がイマイチわからなかった(`util.log` で雑に吐けばいい?)ので issue にしておきます。

**Comment by kanreisa** [comment]
ありがとうございます。
だいぶ古いコードで util.log も deprecated になっているのでもし PR 出されるのでしたら雑な感じで構いません。
gamma の開発はもうやっていませんので、粗が気になるのであれば [EPGStation](https://github.com/Chinachu/Chinachu/wiki/Links#mirakurun) 等をお勧めします。

**Comment by KOBA789** [comment]
なるほど〜〜(浦島太郎でした)
