### ISSUE TITLE
特定のチャンネルが表示されない

### ISSUE THREAD

**Issue by Miutaku** [Chinachu/Chinachu#348]
mirakurunのchannels.ymlにはAKT秋田テレビがあるのにChinachuのEPGには表示されていません。channel '21'の値は間違っていません。それ以外のチャンネルは正常に表示されています。chinachu updateにてEPG更新もしています。不具合でしょうか？node.jsは8.9.4ですのでこちらは問題ないかと思うのですが…

chinachu@REC-SERVER:/usr/local/etc/mirakurun$ cat channels.yml
- name: ＮＨＫＥテレ
  type: GR
  channel: '13'
- name: ＮＨＫ総合
  type: GR
  channel: '15'
- name: 秋田放送
  type: GR
  channel: '17'
- name: ＴＵＹ
  type: GR
  channel: '20'
- name: ＡＫＴ秋田テレビ
  type: GR
  channel: '21'
- name: Ｏ
  type: GR
  channel: '27'
- name: 秋田朝日放送
  type: GR
  channel: '29'
- name: WOWOW Live
  type: BS
  channel: BS05_0
  serviceId: 192
  isDisabled: true
- name: BS11
  type: BS
  channel: BS09_0
  serviceId: 211
- name: WOWOW Cinema
  type: BS
  channel: BS05_1
  serviceId: 193
  isDisabled: true
- name: NHK BS1 (Sub)
  type: BS
  channel: BS15_0
  serviceId: 102
- name: NHK BS1
  type: BS
  channel: BS15_0
  serviceId: 101
- name: NHK BS Premium
  type: BS
  channel: BS15_1
  serviceId: 103
- name: NHK BS Premium (Sub)
  type: BS
  channel: BS15_1
  serviceId: 104
- name: BS Nippon
  type: BS
  channel: BS13_0
  serviceId: 141
- name: BS-TBS
  type: BS
  channel: BS01_1
  serviceId: 161
- name: BS Nippon (Sub)
  type: BS
  channel: BS13_0
  serviceId: 142
- name: BS SPTV
  type: BS
  channel: BS11_1
  serviceId: 241
  isDisabled: true
- name: BS Asahi (Sub)
  type: BS
  channel: BS01_0
  serviceId: 152
- name: BS JAPAN
  type: BS
  channel: BS03_1
  serviceId: 171
- name: BS Fuji
  type: BS
  channel: BS13_1
  serviceId: 181
- name: WOWOW Prime
  type: BS
  channel: BS03_0
  serviceId: 191
  isDisabled: true
- name: BS Asahi
  type: BS
  channel: BS01_0
  serviceId: 151
- name: SPTV Promo
  type: CS
  channel: CS4
  serviceId: 100
- name: TV Asahi Ch. 1
  type: CS
  channel: CS2
  serviceId: 298
  isDisabled: true
- name: TV Asahi Ch. 2
  type: CS
  channel: CS2
  serviceId: 299
  isDisabled: true
- name: AT-X
  type: CS
  channel: CS16
  serviceId: 333
  isDisabled: true
- name: AT-X HD
  type: SKY
  channel: ATXHD
  serviceId: 33435
  satelite: JCSAT3A
  isDisabled: true
- name: BS SPTV
  type: SKY
  channel: CH585
  serviceId: 33353
  satelite: JCSAT3A
  isDisabled: true
- name: AXN HD
  type: SKY
  channel: AXNHD
  serviceId: 33418
  satelite: JCSAT4A
  isDisabled: true

**Comment by kanreisa** [comment]
不具合は特に確認されていません
