### ISSUE TITLE
node npm のシンボリックリンク先が存在しない

### ISSUE THREAD

**Issue by epgdatacapbon** [Chinachu/Chinachu#349]
Debian stretchにてWikiの通りに（実行ユーザーはchinachuとした）
クリーンインストールしたところ、
/home/chinachu/chinachu/.nave/node
/home/chinachu/chinachu/.nave/npm
がリンク切れとなっていた。この状態では
pm2 start processes.json
でエラーが表示されるため、
ln -s /usr/bin/node /home/chinachu/chinachu/.nave/node
ln -s /usr/bin/npm /home/chinachu/chinachu/.nave/npm
のようにリンクを張り直す必要がある。

**Comment by Kumassy** [comment]
`wget` はインストールされていましたか？

こちらは CentOS 7 minimum でインストールしましたが、同じく chinachu/.nave/node chinachu/.nave/npm がリンク切れとなる不具合が発生しました。wget がインストールされておらず、スクリプトが途中で止まってしまったのが原因だったようです。

wget をインストールすれば解決しました。

**Comment by epgdatacapbon** [comment]
debian stretchなのでwgetはインストールしています。
nodeも
>wget -qO- https://deb.nodesource.com/setup_8.x | bash -
>apt-get install nodejs
によりインストールしています。

むしろcurlをインストールしていないため、これが原因の可能性がありますでしょうか？

**Comment by kanreisa** [comment]
`./chinachu installer` で解決するはずです！
