### ISSUE TITLE
chinachu インストールでエラーが出る

### ISSUE THREAD

**Issue by hyde-tech** [Chinachu/Chinachu#351]
当方、raspberry pi 3 でTVサーバーを動かしています。
PX-S1UD の2本差しで Mirakurun を使ってリアルタイム視聴も録画もできています。

chinachu をインストールしようとすると 
`g++ '-DV8_TARGET_ARCH_ARM' '-DENABLE_DISASSEMBLER' '-DV8_I18N_SUPPORT' -I../deps/v8  -pthread -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -mfloat-abi=hard -marm -fdata-sections -ffunction-sections -O3 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /home/hyde/chinachu/.nave/src/6.11.2/out/Release/.deps//home/hyde/chinachu/.nave/src/6.11.2/out/Release/obj.target/v8_libplatform/deps/v8/src/libplatform/default-platform.o.d.raw  -O2 -w -pipe -march=native -c -o /home/hyde/chinachu/.nave/src/6.11.2/out/Release/obj.target/v8_libplatform/deps/v8/src/libplatform/default-platform.o ../deps/v8/src/libplatform/default-platform.cc
*** Error in `g++': double free or corruption (top): 0x00282710 ***
deps/v8/tools/gyp/v8_libplatform.target.mk:97: recipe for target '/home/hyde/chinachu/.nave/src/6.11.2/out/Release/obj.target/v8_libplatform/deps/v8/src/libplatform/default-platform.o' failed
make[1]: *** [/home/hyde/chinachu/.nave/src/6.11.2/out/Release/obj.target/v8_libplatform/deps/v8/src/libplatform/default-platform.o] 中止
make[1]: *** 未完了のジョブを待っています....
make[1]: Leaving directory '/home/hyde/chinachu/.nave/src/6.11.2/out'
Makefile:73: recipe for target 'node' failed
make: *** [node] Error 2
Failed to make 6.11.2
fail
`
となってその後エラーが続きます。
何が足りないのでしょうか？

**Comment by kanreisa** [comment]
ARM 環境はビルトイン Node.js インストーラーが利用できません。
各自工夫していただければと思います
