### ISSUE TITLE
開始数秒で動画が切れることがある。

### ISSUE THREAD

**Issue by opticalmaterials** [Chinachu/Chinachu#364]
**どのようなバグですか？**
表題通りの内容となります。
関連：開始数秒、動画が切れることがある。 #340

そのため、関連issueを参考に、不要なチャンネル設定をisDisable: trueにし、地上波以外は受信しないようにしております。

**再現方法**
再現方法はわかりません。毎回起こるわけではなく、起こることがある現象です。

**期待する動作**
指定した番組が終了まで録画されることが最も望む動作です。

**スクリーンショット**
ありませんので、ログを記載いたします。

```
4 Jul 20:43:23 - SPAWN: node app-scheduler.js (pid=28472)
4 Jul 20:43:23 - STREAM: ./log/scheduler
4 Jul 20:43:29 - EXIT: node app-scheduler.js (pid=28472)
4 Jul 20:43:30 - READ: `/home/pi/chinachu/data/reserves.json` is updated.
4 Jul 20:53:23 - SPAWN: node app-scheduler.js (pid=29622)
4 Jul 20:53:23 - STREAM: ./log/scheduler
4 Jul 20:53:29 - EXIT: node app-scheduler.js (pid=29622)
4 Jul 20:53:30 - READ: `/home/pi/chinachu/data/reserves.json` is updated.
4 Jul 20:53:47 - PREPARE: #381ocd7v84 2019-07-04T20:54:00+0900 [日テレ１] THE MUSIC DAY NEWS　櫻井翔＆天龍が情報解禁！激かわアニー登場
4 Jul 20:53:47 - WRITE: /home/pi/chinachu/data/recording.json
4 Jul 20:54:04 - RECORD: #381ocd7v84 2019-07-04T20:54:00+0900 [日テレ１] THE MUSIC DAY NEWS　櫻井翔＆天龍が情報解禁！激かわアニー登場
4 Jul 20:54:04 - STREAM: /mnt/nas/[190704-2054][GR25][日テレ１]THE MUSIC DAY NEWS[字]　櫻井翔＆天龍が情報解禁！激かわアニー登場.m2ts
4 Jul 20:54:04 - WRITE: /home/pi/chinachu/data/recording.json
4 Jul 20:54:43 - WRITE: /home/pi/chinachu/data/recorded.json
4 Jul 20:54:43 - WRITE: /home/pi/chinachu/data/recording.json
4 Jul 20:54:43 - WRITE: /home/pi/chinachu/data/reserves.json
4 Jul 20:54:43 - FIN: #381ocd7v84 2019-07-04T20:54:00+0900 [日テレ１] THE MUSIC DAY NEWS　櫻井翔＆天龍が情報解禁！激かわアニー登場
4 Jul 20:54:44 - READ: `/home/pi/chinachu/data/reserves.json` is updated.
4 Jul 20:54:44 - READ: `/home/pi/chinachu/data/recorded.json` is updated.
```

見かけ上は、正常に終了しているように見受けられますが、5分ほどの番組ですので、終了は21:00頃になっているはずです。

**再現環境 (できるだけ詳しく):**
 - OS: Raspbian Stretch Lite
 - CPU: Broadcom BCM2837 ARM Cortex-A53(4コア、1.2 GHz) Raspberry Pi3 
 - Browser Google Chrome 75.0.3770.100 
 - Version gamma 最新版と思っておりますが、4月にリポジトリから取得しコンパイルしたものとなります。申し訳ございません。

**追加情報**
この現象以外は、大変快適に使わさせてもらっています。大変お手数ですが、問題解決に向けたアドバイスを頂ければと思います。よろしくお願いいたします。

**Comment by opticalmaterials** [comment]
いろいろなパターンや時間で調査しておりましたが、どうも手動予約した際に開始直後に終了判定になってしまう事が多いように見受けられます。
予約のタイミングも番組開始直前というわけでもなく、色々なタイミングを試していますが、いまいち傾向がつかめない状態です。
自動予約は今のところ問題が出ておりませんのですが、自動予約と手動予約で内部的な動きが違うようにも思えませんが、遭遇した状態を報告させていただきます。

**Comment by kanreisa** [comment]
こんばんは。

以下のような理由が考えられます
* チューナーが足りていない（チャンネルが競合してしまっている）
* 単純に処理落ち (Mirakurun でエラーが出ていなければここは特に問題ないと思います）

もし可能であれば、再現している同じ時間の Mirakurun のログもあわせてご確認いただけると幸いです。

※ 録画済みの番組のページの下の方に「録画パラメーター」というのがあると思いますが、そこに `priority=n` という部分があるとおもいます。録画が切れてしまっているものは、もしかしたらそこが違っているかもしれません。
※ プロジェクトの開発リソースが足りていないため Chinachu on ARM は現在のところサポートされていません。(Mirakurun はサポートしていますが性能によります)

どうぞよろしくお願いいたします。

**Comment by opticalmaterials** [comment]
返答ありがとうございます。
当時の録画済み状況からみると、録画が混雑していることはありませんでした。
当時のmirakurunのログが流れてしまっているため、再発しましたらログを保持して再度報告させていただきます。
なお、ご指摘のありました、録画パラメータに関しては、正常に録画が完了したものと同等でした。

また、armはchinachuではサポート外とのことですので、一旦クローズさせていただき、発生状態のmirakurunのログが取得でき次第issueを投稿させて頂きます。
