### ISSUE TITLE
pm2へのスタートアップ登録ができない

### ISSUE THREAD

**Issue by stu2005** [Chinachu/Chinachu#367]
Gamma Installation V2にしたがってラズベリーパイ3(Raspbian Buster)にインストール、pm2へのスタートアップ登録をしようとするのですが、下記のエラーが出力されて失敗します。
```
[PM2][ERROR] Error: Interpreter .nave/node is NOT AVAILABLE in PATH. (type 'which .nave/node' to double check.)
[PM2][ERROR] Error: Interpreter .nave/node is NOT AVAILABLE in PATH. (type 'which .nave/node' to double check.)
```
エラーを解消して正しく設定するにはどうすればよいでしょうか？

**Comment by stu2005** [comment]
追記
調べた結果、.nave/nodeが存在していないようです。これはバグか何かでしょうか?間違ってたらすみません

**Comment by akimasa** [comment]
[Gamma Installation V2](https://github.com/Chinachu/Chinachu/wiki/Gamma-Installation-V2)の手順3.には次のような記述があります。
> \# Auto を選択 (ARM の場合は Node.js のインストールはできません)

Raspberry PiのプラットフォームはARMなので、node.jsが自動的にインストールされません。
したがって、バグではなく、そういうものなのではないかと思います。

ちなみに、**Node.jsを手動でインストールした上で** [こちらのブログ](http://k-pi.hatenablog.com/entry/2017/07/30/151659)の手順9.を参考に実行ファイルをコピーする（あるいは`ln -sf /usr/bin/node .nave/node; ln -sf /usr/bin/npm .nave/npm`でシンボリックリンクを張る）とうまくいくと思います。

**Comment by stu2005** [comment]
仕様なのですね。ありがとうございます
