### ISSUE TITLE
地デジ波のテレビ局ログの取得が遅い

### ISSUE THREAD

**Issue by trimethia** [Chinachu/Chinachu#369]
環境：
- raspberry 4 b 上で最新chinachu+mirakurunを使用している
- chinachu を Firefox 74.0 (64-bit) で開いて視聴している
- EPGの取得やチャンネルの視聴が問題なく動作している

現象：
手元の環境では地上放送のテレビ局ログの取得が非常に遅いようです。
具体的には、環境構築後に6時間毎に一つのログが表示されるようになっている感じです。

質問：
1. テレビ局ログの取得が遅い原因として何が考えられますでしょうか？mirakurun側の問題？
2. 自分で任意の画像を局のログとして設定することが可能でしょうか？

よろしくお願いいたします。

**Comment by masnagam** [comment]
実際，動かして確認したわけではないので，参考程度と考えてください．以下，「ログ」とは「ロゴ」の間違いだとして書きます．

1. バグではないと思います
2. 多分できない

### バグではないと考える根拠

まず，TSからロゴを取得しているのはMirakurunです．CDTセクションに入っています．
https://github.com/Chinachu/Mirakurun/blob/master/src/Mirakurun/TSFilter.ts#L592

TSに含まれているので，当然チューナーからデータを読み出している状態でないと上記は動作しません．/api/xxx/streamを利用しない状態で放置しているのだとすると，MirakurunはサービスのスキャンおよびEPGデータ取得時しかチューナーからデータを読み出しません．地デジだと各チャンネル１，２分で終わってしまいます．

私が調べた限りでは，１，２分ではロゴを取得できない場合が多いです．
https://github.com/masnagam/mirakc-arib/blob/master/src/main.cc#L344

Mirakurunは６種類あるロゴの一番サイズが大きいものだけを使いますが，これが１，２分の間に運良く取得できる可能性は高くはありません．

ロゴを取得する一番確実な方法は，/api/xxx/streamを１０分以上受信することです．つまり，Chinachuで１０分以上録画・ライブ視聴すれば多分取得できます．

`curl`が使えるなら以下でも取得できると思います．

```console
timeout 10m curl -fsSL http://<mirakuruh>:40772/api/channel/GR/<channel>/stream >/dev/null
```

### 多分できないと考える根拠

`logo`で検索してもそれっぽいコードが見つからないから．
https://github.com/Chinachu/Chinachu/search?q=logo&unscoped_q=logo

**Comment by kanreisa** [comment]
ありがとうございます。
@masnagam さんの仰る通り、これはバグではなく仕様となります。
