### ISSUE TITLE
./chinachu service wui executeを実行するとエラーが出力される

### ISSUE THREAD

**Issue by Tidus7** [Chinachu/Chinachu#370]
# ./chinachu service wui execute
Client {
  basePath: '/api',
  docsPath: '/docs',
  priority: 0,
  host: '',
  port: 40772,
  socketPath: '/var/run/mirakurun.sock',
  userAgent: 'Chinachu/0.10.1-gamma.0 (wui)',
  _userAgent: 'MirakurunClient/2.15.0 Node/v10.16.3 (linux)' }
============================================================
Detected Private IPv4: [ '192.xxx.xxx.xxx' ]
Selected Private IPv4 for Open Server: 192.xxx.xxx.xxx
NOTE: set `wuiOpenHost` to fix address for listen.   
============================================================
uncaughtException: Error: EACCES: permission denied, open '/mnt/hdd1/chinachu/data/reserves.json'
20 Apr 18:25:23 - HTTP Open Server Listening on { address: '192.168.150.113', family: 'IPv4', port: 20772 }
20 Apr 18:25:23 - HTTP Open Server mDNS advertising started.
20 Apr 18:25:23 - READ: `/mnt/hdd1/chinachu/rules.json` is updated.
20 Apr 18:25:23 - READ: `/mnt/hdd1/chinachu/data/schedule.json` is updated.

何度かinstallし直しましたが、同じエラーが出力されます。

**Comment by kanreisa** [comment]
> uncaughtException: Error: EACCES: permission denied, open '/mnt/hdd1/chinachu/data/reserves.json'
20 Apr 18:25:23 - HTTP Open Server Listening on { address: '192.168.150.113', family: 'IPv4', port: 20772 }

ということで、実行ユーザーかファイルの owner かパーミッションが正しく設定されていないと思います。確認してみてください。

**Comment by Tidus7** [comment]
$ cd /mnt/hdd1/chinachu/data/
@raspberrypi:/mnt/hdd1/chinachu/data $ ls
schedule.json

reserves.jsonというファイルが存在しないように見えます。

**Comment by Tidus7** [comment]
早速のご回答ありがとうございます。

$ cd /mnt/hdd1/chinachu/data/
/mnt/hdd1/chinachu/data $ ls
schedule.json

"reserves.json"というファイルが存在しないように見受けられます。

**Comment by kanreisa** [comment]
その後解決はしましたでしょうか？
実行ユーザーのパーミッションが正しくない等の原因が考えられます。
何度かインストールして再現されるようですので、インストール手順そのものが間違っている可能性があります。
公式の手順通りに進めていただけますと問題なく動作するかと思います。

何の OS で、何をどうやってインストールしたかなど、環境情報を詳しく教えていただけないと、解決策がみつかりません。バグではなさそうなのでクローズしておきますが、引き続きこのスレッドに追記していただけます。
