### ISSUE TITLE
タイトルに半角の<>が含まれているとき、ストリーミング再生に失敗する

### ISSUE THREAD

**Issue by hts-ozeki** [Chinachu/Chinachu#374]
まず、タイトルに半角の<>が含まれる番組を録画します。
次にこの番組をストリーミング再生します。XSPFファイルを生成しVLCに読ませるのですが、
このとき生成されるXSPFファイルを見ると、タイトルに含まれる半角の<>がエスケープされずに
出力されます。VLCはこのようなXSPFファイルを受け付けず、結果ストリーミング再生できません。
例として挙げると、このようなファイルです。

```
<?xml version="1.0" encoding="UTF-8"?>
<playlist version="1" xmlns="http://xspf.org/ns/0/">
<trackList>
<track>
<location>http://***.***.***.***:20772/api/recorded/*******/watch.m2ts?ext=m2ts&amp;c%3Av=copy&amp;c%3Aa=copy&amp;prefix=http%3A%2F%2F***.***.***.***%3A20772%2Fapi%2Frecorded%2F*******%2F</location>
<title>頭文字[イニシャル]Ｄ<HDリマスター></title>
</track>
</trackList>
</playlist>

```
使っているのは2015年頃cloneしたソースのようです。bcf46cddc1645d547994c4429c418f6dbd58881a かな？
自分でtarボールに固めた時にそんなファイル名を付けてたのであってると思います。

**Comment by hts-ozeki** [comment]
ごめんなさい。tarボールに固める時にファイル名を間違えたようです。
2020/01/26頃にcloneしたソースでした。
(95f28b84fed9490104eb8a7df6a64d7c092ea5e3)
現行ソースでもおそらく同じ問題が起きると思われます。

対策としては、api/script-recorded-program-watch.vm.js の
xspfファイルを生成するあたりで、出力する文字列を改変します。
-------------------------
function main(avinfo) {
    :  省略
 			var target = prefix + 'watch.' + ext  + url.parse(request.url).search;
+			var mangled_title = program.title.replace(/</g, '&lt;')
+			        .replace(/>/g, '&gt;')
+			        .replace(/&/g, '&amp;');
    :  省略
 			response.write('<track>\n<location>' + target.replace(/&/g, '&amp;') + '</location>\n');
-			response.write('<title>' + program.title + '</title>\n</track>\n');
+			response.write('<title>' + mangled_title + '</title>\n</track>\n');
 			response.write('</trackList>\n');
 			response.write('</playlist>\n');
-------------------------
 これで当方ではうまく動いています。

**Comment by kanreisa** [comment]
ご報告いただきましてありがとうございました。
修正しました。
